// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupCreateRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupCreateRequest) Reset()         { *m = GroupCreateRequest{} }
func (m *GroupCreateRequest) String() string { return proto.CompactTextString(m) }
func (*GroupCreateRequest) ProtoMessage()    {}
func (*GroupCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{0}
}

func (m *GroupCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupCreateRequest.Unmarshal(m, b)
}
func (m *GroupCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupCreateRequest.Marshal(b, m, deterministic)
}
func (m *GroupCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupCreateRequest.Merge(m, src)
}
func (m *GroupCreateRequest) XXX_Size() int {
	return xxx_messageInfo_GroupCreateRequest.Size(m)
}
func (m *GroupCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupCreateRequest proto.InternalMessageInfo

func (m *GroupCreateRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type GroupCreateResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Group                *Group       `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupCreateResponse) Reset()         { *m = GroupCreateResponse{} }
func (m *GroupCreateResponse) String() string { return proto.CompactTextString(m) }
func (*GroupCreateResponse) ProtoMessage()    {}
func (*GroupCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{1}
}

func (m *GroupCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupCreateResponse.Unmarshal(m, b)
}
func (m *GroupCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupCreateResponse.Marshal(b, m, deterministic)
}
func (m *GroupCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupCreateResponse.Merge(m, src)
}
func (m *GroupCreateResponse) XXX_Size() int {
	return xxx_messageInfo_GroupCreateResponse.Size(m)
}
func (m *GroupCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupCreateResponse proto.InternalMessageInfo

func (m *GroupCreateResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupCreateResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GroupCreateResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupOwnRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupOwnRequest) Reset()         { *m = GroupOwnRequest{} }
func (m *GroupOwnRequest) String() string { return proto.CompactTextString(m) }
func (*GroupOwnRequest) ProtoMessage()    {}
func (*GroupOwnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{2}
}

func (m *GroupOwnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupOwnRequest.Unmarshal(m, b)
}
func (m *GroupOwnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupOwnRequest.Marshal(b, m, deterministic)
}
func (m *GroupOwnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupOwnRequest.Merge(m, src)
}
func (m *GroupOwnRequest) XXX_Size() int {
	return xxx_messageInfo_GroupOwnRequest.Size(m)
}
func (m *GroupOwnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupOwnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupOwnRequest proto.InternalMessageInfo

type GroupOwnResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Group                *Group       `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupOwnResponse) Reset()         { *m = GroupOwnResponse{} }
func (m *GroupOwnResponse) String() string { return proto.CompactTextString(m) }
func (*GroupOwnResponse) ProtoMessage()    {}
func (*GroupOwnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{3}
}

func (m *GroupOwnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupOwnResponse.Unmarshal(m, b)
}
func (m *GroupOwnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupOwnResponse.Marshal(b, m, deterministic)
}
func (m *GroupOwnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupOwnResponse.Merge(m, src)
}
func (m *GroupOwnResponse) XXX_Size() int {
	return xxx_messageInfo_GroupOwnResponse.Size(m)
}
func (m *GroupOwnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupOwnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupOwnResponse proto.InternalMessageInfo

func (m *GroupOwnResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupOwnResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GroupOwnResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupListRequest) Reset()         { *m = GroupListRequest{} }
func (m *GroupListRequest) String() string { return proto.CompactTextString(m) }
func (*GroupListRequest) ProtoMessage()    {}
func (*GroupListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{4}
}

func (m *GroupListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupListRequest.Unmarshal(m, b)
}
func (m *GroupListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupListRequest.Marshal(b, m, deterministic)
}
func (m *GroupListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupListRequest.Merge(m, src)
}
func (m *GroupListRequest) XXX_Size() int {
	return xxx_messageInfo_GroupListRequest.Size(m)
}
func (m *GroupListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupListRequest proto.InternalMessageInfo

type GroupListResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Groups               []*Group     `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupListResponse) Reset()         { *m = GroupListResponse{} }
func (m *GroupListResponse) String() string { return proto.CompactTextString(m) }
func (*GroupListResponse) ProtoMessage()    {}
func (*GroupListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{5}
}

func (m *GroupListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupListResponse.Unmarshal(m, b)
}
func (m *GroupListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupListResponse.Marshal(b, m, deterministic)
}
func (m *GroupListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupListResponse.Merge(m, src)
}
func (m *GroupListResponse) XXX_Size() int {
	return xxx_messageInfo_GroupListResponse.Size(m)
}
func (m *GroupListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupListResponse proto.InternalMessageInfo

func (m *GroupListResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupListResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GroupListResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GroupMembersRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMembersRequest) Reset()         { *m = GroupMembersRequest{} }
func (m *GroupMembersRequest) String() string { return proto.CompactTextString(m) }
func (*GroupMembersRequest) ProtoMessage()    {}
func (*GroupMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{6}
}

func (m *GroupMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMembersRequest.Unmarshal(m, b)
}
func (m *GroupMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMembersRequest.Marshal(b, m, deterministic)
}
func (m *GroupMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMembersRequest.Merge(m, src)
}
func (m *GroupMembersRequest) XXX_Size() int {
	return xxx_messageInfo_GroupMembersRequest.Size(m)
}
func (m *GroupMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMembersRequest proto.InternalMessageInfo

func (m *GroupMembersRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type GroupMembersResponse struct {
	Code                 ResponseCode   `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error         `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Members              []*GroupMember `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GroupMembersResponse) Reset()         { *m = GroupMembersResponse{} }
func (m *GroupMembersResponse) String() string { return proto.CompactTextString(m) }
func (*GroupMembersResponse) ProtoMessage()    {}
func (*GroupMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{7}
}

func (m *GroupMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMembersResponse.Unmarshal(m, b)
}
func (m *GroupMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMembersResponse.Marshal(b, m, deterministic)
}
func (m *GroupMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMembersResponse.Merge(m, src)
}
func (m *GroupMembersResponse) XXX_Size() int {
	return xxx_messageInfo_GroupMembersResponse.Size(m)
}
func (m *GroupMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMembersResponse proto.InternalMessageInfo

func (m *GroupMembersResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupMembersResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GroupMembersResponse) GetMembers() []*GroupMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type GroupApplyRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupApplyRequest) Reset()         { *m = GroupApplyRequest{} }
func (m *GroupApplyRequest) String() string { return proto.CompactTextString(m) }
func (*GroupApplyRequest) ProtoMessage()    {}
func (*GroupApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{8}
}

func (m *GroupApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupApplyRequest.Unmarshal(m, b)
}
func (m *GroupApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupApplyRequest.Marshal(b, m, deterministic)
}
func (m *GroupApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupApplyRequest.Merge(m, src)
}
func (m *GroupApplyRequest) XXX_Size() int {
	return xxx_messageInfo_GroupApplyRequest.Size(m)
}
func (m *GroupApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupApplyRequest proto.InternalMessageInfo

func (m *GroupApplyRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type GroupApplyResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupApplyResponse) Reset()         { *m = GroupApplyResponse{} }
func (m *GroupApplyResponse) String() string { return proto.CompactTextString(m) }
func (*GroupApplyResponse) ProtoMessage()    {}
func (*GroupApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{9}
}

func (m *GroupApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupApplyResponse.Unmarshal(m, b)
}
func (m *GroupApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupApplyResponse.Marshal(b, m, deterministic)
}
func (m *GroupApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupApplyResponse.Merge(m, src)
}
func (m *GroupApplyResponse) XXX_Size() int {
	return xxx_messageInfo_GroupApplyResponse.Size(m)
}
func (m *GroupApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupApplyResponse proto.InternalMessageInfo

func (m *GroupApplyResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupApplyResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type GroupApplyMembersRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupApplyMembersRequest) Reset()         { *m = GroupApplyMembersRequest{} }
func (m *GroupApplyMembersRequest) String() string { return proto.CompactTextString(m) }
func (*GroupApplyMembersRequest) ProtoMessage()    {}
func (*GroupApplyMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{10}
}

func (m *GroupApplyMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupApplyMembersRequest.Unmarshal(m, b)
}
func (m *GroupApplyMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupApplyMembersRequest.Marshal(b, m, deterministic)
}
func (m *GroupApplyMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupApplyMembersRequest.Merge(m, src)
}
func (m *GroupApplyMembersRequest) XXX_Size() int {
	return xxx_messageInfo_GroupApplyMembersRequest.Size(m)
}
func (m *GroupApplyMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupApplyMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupApplyMembersRequest proto.InternalMessageInfo

func (m *GroupApplyMembersRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type GroupApplyMembersResponse struct {
	Code                 ResponseCode   `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error         `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Members              []*GroupMember `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GroupApplyMembersResponse) Reset()         { *m = GroupApplyMembersResponse{} }
func (m *GroupApplyMembersResponse) String() string { return proto.CompactTextString(m) }
func (*GroupApplyMembersResponse) ProtoMessage()    {}
func (*GroupApplyMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{11}
}

func (m *GroupApplyMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupApplyMembersResponse.Unmarshal(m, b)
}
func (m *GroupApplyMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupApplyMembersResponse.Marshal(b, m, deterministic)
}
func (m *GroupApplyMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupApplyMembersResponse.Merge(m, src)
}
func (m *GroupApplyMembersResponse) XXX_Size() int {
	return xxx_messageInfo_GroupApplyMembersResponse.Size(m)
}
func (m *GroupApplyMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupApplyMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupApplyMembersResponse proto.InternalMessageInfo

func (m *GroupApplyMembersResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupApplyMembersResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GroupApplyMembersResponse) GetMembers() []*GroupMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type GroupOperRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Oper                 int32    `protobuf:"varint,2,opt,name=oper,proto3" json:"oper,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupOperRequest) Reset()         { *m = GroupOperRequest{} }
func (m *GroupOperRequest) String() string { return proto.CompactTextString(m) }
func (*GroupOperRequest) ProtoMessage()    {}
func (*GroupOperRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{12}
}

func (m *GroupOperRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupOperRequest.Unmarshal(m, b)
}
func (m *GroupOperRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupOperRequest.Marshal(b, m, deterministic)
}
func (m *GroupOperRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupOperRequest.Merge(m, src)
}
func (m *GroupOperRequest) XXX_Size() int {
	return xxx_messageInfo_GroupOperRequest.Size(m)
}
func (m *GroupOperRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupOperRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupOperRequest proto.InternalMessageInfo

func (m *GroupOperRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupOperRequest) GetOper() int32 {
	if m != nil {
		return m.Oper
	}
	return 0
}

func (m *GroupOperRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GroupOperResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupOperResponse) Reset()         { *m = GroupOperResponse{} }
func (m *GroupOperResponse) String() string { return proto.CompactTextString(m) }
func (*GroupOperResponse) ProtoMessage()    {}
func (*GroupOperResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{13}
}

func (m *GroupOperResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupOperResponse.Unmarshal(m, b)
}
func (m *GroupOperResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupOperResponse.Marshal(b, m, deterministic)
}
func (m *GroupOperResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupOperResponse.Merge(m, src)
}
func (m *GroupOperResponse) XXX_Size() int {
	return xxx_messageInfo_GroupOperResponse.Size(m)
}
func (m *GroupOperResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupOperResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupOperResponse proto.InternalMessageInfo

func (m *GroupOperResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupOperResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type GroupContriRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Level                int32    `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupContriRequest) Reset()         { *m = GroupContriRequest{} }
func (m *GroupContriRequest) String() string { return proto.CompactTextString(m) }
func (*GroupContriRequest) ProtoMessage()    {}
func (*GroupContriRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{14}
}

func (m *GroupContriRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupContriRequest.Unmarshal(m, b)
}
func (m *GroupContriRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupContriRequest.Marshal(b, m, deterministic)
}
func (m *GroupContriRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupContriRequest.Merge(m, src)
}
func (m *GroupContriRequest) XXX_Size() int {
	return xxx_messageInfo_GroupContriRequest.Size(m)
}
func (m *GroupContriRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupContriRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupContriRequest proto.InternalMessageInfo

func (m *GroupContriRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupContriRequest) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type GroupContriResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupContriResponse) Reset()         { *m = GroupContriResponse{} }
func (m *GroupContriResponse) String() string { return proto.CompactTextString(m) }
func (*GroupContriResponse) ProtoMessage()    {}
func (*GroupContriResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{15}
}

func (m *GroupContriResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupContriResponse.Unmarshal(m, b)
}
func (m *GroupContriResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupContriResponse.Marshal(b, m, deterministic)
}
func (m *GroupContriResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupContriResponse.Merge(m, src)
}
func (m *GroupContriResponse) XXX_Size() int {
	return xxx_messageInfo_GroupContriResponse.Size(m)
}
func (m *GroupContriResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupContriResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupContriResponse proto.InternalMessageInfo

func (m *GroupContriResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupContriResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type Group struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	GroupName            string   `protobuf:"bytes,2,opt,name=GroupName,proto3" json:"GroupName,omitempty"`
	GroupLeader          string   `protobuf:"bytes,3,opt,name=GroupLeader,proto3" json:"GroupLeader,omitempty"`
	GroupDeclaration     string   `protobuf:"bytes,4,opt,name=GroupDeclaration,proto3" json:"GroupDeclaration,omitempty"`
	MemberCnt            int32    `protobuf:"varint,5,opt,name=MemberCnt,proto3" json:"MemberCnt,omitempty"`
	MemberTotal          int32    `protobuf:"varint,6,opt,name=MemberTotal,proto3" json:"MemberTotal,omitempty"`
	GroupLevel           int32    `protobuf:"varint,7,opt,name=GroupLevel,proto3" json:"GroupLevel,omitempty"`
	ContriCurrent        int32    `protobuf:"varint,8,opt,name=ContriCurrent,proto3" json:"ContriCurrent,omitempty"`
	ContriLevelUp        int32    `protobuf:"varint,9,opt,name=ContriLevelUp,proto3" json:"ContriLevelUp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{16}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *Group) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Group) GetGroupLeader() string {
	if m != nil {
		return m.GroupLeader
	}
	return ""
}

func (m *Group) GetGroupDeclaration() string {
	if m != nil {
		return m.GroupDeclaration
	}
	return ""
}

func (m *Group) GetMemberCnt() int32 {
	if m != nil {
		return m.MemberCnt
	}
	return 0
}

func (m *Group) GetMemberTotal() int32 {
	if m != nil {
		return m.MemberTotal
	}
	return 0
}

func (m *Group) GetGroupLevel() int32 {
	if m != nil {
		return m.GroupLevel
	}
	return 0
}

func (m *Group) GetContriCurrent() int32 {
	if m != nil {
		return m.ContriCurrent
	}
	return 0
}

func (m *Group) GetContriLevelUp() int32 {
	if m != nil {
		return m.ContriLevelUp
	}
	return 0
}

type GroupMember struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	Power                int32    `protobuf:"varint,4,opt,name=Power,proto3" json:"Power,omitempty"`
	ContriToday          int32    `protobuf:"varint,5,opt,name=ContriToday,proto3" json:"ContriToday,omitempty"`
	ContriTotal          int32    `protobuf:"varint,6,opt,name=ContriTotal,proto3" json:"ContriTotal,omitempty"`
	Job                  int32    `protobuf:"varint,7,opt,name=Job,proto3" json:"Job,omitempty"`
	OffLineTime          int32    `protobuf:"varint,8,opt,name=OffLineTime,proto3" json:"OffLineTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMember) Reset()         { *m = GroupMember{} }
func (m *GroupMember) String() string { return proto.CompactTextString(m) }
func (*GroupMember) ProtoMessage()    {}
func (*GroupMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{17}
}

func (m *GroupMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMember.Unmarshal(m, b)
}
func (m *GroupMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMember.Marshal(b, m, deterministic)
}
func (m *GroupMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMember.Merge(m, src)
}
func (m *GroupMember) XXX_Size() int {
	return xxx_messageInfo_GroupMember.Size(m)
}
func (m *GroupMember) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMember.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMember proto.InternalMessageInfo

func (m *GroupMember) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GroupMember) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupMember) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GroupMember) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *GroupMember) GetContriToday() int32 {
	if m != nil {
		return m.ContriToday
	}
	return 0
}

func (m *GroupMember) GetContriTotal() int32 {
	if m != nil {
		return m.ContriTotal
	}
	return 0
}

func (m *GroupMember) GetJob() int32 {
	if m != nil {
		return m.Job
	}
	return 0
}

func (m *GroupMember) GetOffLineTime() int32 {
	if m != nil {
		return m.OffLineTime
	}
	return 0
}

func init() {
	proto.RegisterType((*GroupCreateRequest)(nil), "msg.GroupCreateRequest")
	proto.RegisterType((*GroupCreateResponse)(nil), "msg.GroupCreateResponse")
	proto.RegisterType((*GroupOwnRequest)(nil), "msg.GroupOwnRequest")
	proto.RegisterType((*GroupOwnResponse)(nil), "msg.GroupOwnResponse")
	proto.RegisterType((*GroupListRequest)(nil), "msg.GroupListRequest")
	proto.RegisterType((*GroupListResponse)(nil), "msg.GroupListResponse")
	proto.RegisterType((*GroupMembersRequest)(nil), "msg.GroupMembersRequest")
	proto.RegisterType((*GroupMembersResponse)(nil), "msg.GroupMembersResponse")
	proto.RegisterType((*GroupApplyRequest)(nil), "msg.GroupApplyRequest")
	proto.RegisterType((*GroupApplyResponse)(nil), "msg.GroupApplyResponse")
	proto.RegisterType((*GroupApplyMembersRequest)(nil), "msg.GroupApplyMembersRequest")
	proto.RegisterType((*GroupApplyMembersResponse)(nil), "msg.GroupApplyMembersResponse")
	proto.RegisterType((*GroupOperRequest)(nil), "msg.GroupOperRequest")
	proto.RegisterType((*GroupOperResponse)(nil), "msg.GroupOperResponse")
	proto.RegisterType((*GroupContriRequest)(nil), "msg.GroupContriRequest")
	proto.RegisterType((*GroupContriResponse)(nil), "msg.GroupContriResponse")
	proto.RegisterType((*Group)(nil), "msg.Group")
	proto.RegisterType((*GroupMember)(nil), "msg.GroupMember")
}

func init() { proto.RegisterFile("group.proto", fileDescriptor_e10f4c9b19ad8eee) }

var fileDescriptor_e10f4c9b19ad8eee = []byte{
	// 574 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0x26, 0x4d, 0xd3, 0xda, 0x29, 0x6a, 0xbb, 0x16, 0x89, 0x72, 0x48, 0x59, 0x14, 0x8e, 0x03,
	0x2b, 0x54, 0xff, 0x80, 0xf4, 0xa4, 0x9c, 0x9c, 0x9e, 0x84, 0x1e, 0x9c, 0xbe, 0xa5, 0x97, 0xb9,
	0x52, 0x68, 0xb2, 0x71, 0x93, 0x7a, 0x14, 0xee, 0xdd, 0x17, 0xff, 0x90, 0x3f, 0xc6, 0xff, 0x22,
	0xbb, 0x33, 0xb9, 0x6c, 0x55, 0xa8, 0x0f, 0x45, 0xdf, 0x76, 0xbe, 0xf9, 0x66, 0xe7, 0xeb, 0x37,
	0x9b, 0x29, 0x74, 0x17, 0x5a, 0xad, 0xf3, 0x51, 0xae, 0x55, 0xa9, 0x84, 0x9f, 0x16, 0x8b, 0xc7,
	0x1d, 0xd4, 0x9a, 0x62, 0x39, 0x06, 0x31, 0x35, 0xe9, 0x89, 0xc6, 0xb8, 0xc4, 0x08, 0x3f, 0xaf,
	0xb1, 0x28, 0xc5, 0x01, 0x74, 0x6c, 0xd1, 0xfb, 0x38, 0xc5, 0xd0, 0x1b, 0x7a, 0x87, 0x9d, 0xa8,
	0x06, 0xe4, 0x0d, 0x3c, 0xd8, 0xaa, 0x29, 0x72, 0x95, 0x15, 0x28, 0x9e, 0x41, 0xf3, 0x52, 0x25,
	0xc4, 0xbf, 0x37, 0xee, 0x8f, 0xd2, 0x62, 0x31, 0xaa, 0x92, 0x13, 0x95, 0x60, 0x64, 0xd3, 0xe2,
	0x00, 0x7c, 0xd4, 0x3a, 0x6c, 0x0c, 0xbd, 0xc3, 0xee, 0x18, 0x2c, 0xeb, 0x8d, 0xd6, 0x4a, 0x47,
	0x06, 0x16, 0x43, 0x08, 0x6c, 0xa3, 0xd0, 0x77, 0xf2, 0xb6, 0x5b, 0x44, 0x09, 0xd9, 0x87, 0xfb,
	0x36, 0x3e, 0xbb, 0xce, 0x58, 0xae, 0xdc, 0x40, 0xaf, 0x86, 0xfe, 0xad, 0x1a, 0xc1, 0xad, 0x4f,
	0x97, 0x45, 0x59, 0xc9, 0xb9, 0x81, 0xbe, 0x83, 0xed, 0x53, 0x8f, 0x84, 0x96, 0x6d, 0x5b, 0x84,
	0xfe, 0xd0, 0xff, 0x45, 0x10, 0x67, 0xe4, 0x0b, 0x9e, 0xce, 0x3b, 0x4c, 0xe7, 0xa8, 0x8b, 0x6a,
	0xa4, 0x21, 0xb4, 0x2d, 0xe1, 0x24, 0xe1, 0x81, 0x56, 0xa1, 0xfc, 0xea, 0xc1, 0x60, 0xbb, 0x62,
	0x9f, 0x92, 0x8f, 0xa0, 0x9d, 0xd2, 0xbd, 0xac, 0xb9, 0x57, 0x6b, 0xa6, 0x86, 0x51, 0x45, 0x90,
	0xcf, 0xd9, 0xb8, 0xd7, 0x79, 0xbe, 0xda, 0xec, 0x16, 0xfe, 0x91, 0xdf, 0x2e, 0xd3, 0xf7, 0xa8,
	0x5a, 0xbe, 0x82, 0xb0, 0xbe, 0xfa, 0xaf, 0x9d, 0xfc, 0xe6, 0xc1, 0xa3, 0x3f, 0x94, 0xfd, 0x2f,
	0x3b, 0x2f, 0xaa, 0xcf, 0x22, 0x47, 0xbd, 0x53, 0xbc, 0x10, 0xd0, 0x54, 0x39, 0x52, 0xe3, 0x20,
	0xb2, 0x67, 0xf1, 0x10, 0x5a, 0xeb, 0x02, 0xf5, 0x49, 0x62, 0x3f, 0x80, 0x4e, 0xc4, 0x91, 0xbc,
	0xe0, 0x41, 0xd1, 0xcd, 0xfb, 0x34, 0xfe, 0xb8, 0xda, 0x47, 0x2a, 0x2b, 0xf5, 0x72, 0xb7, 0xea,
	0x01, 0x04, 0x2b, 0xfc, 0x82, 0x2b, 0x96, 0x4d, 0x81, 0xfc, 0x54, 0x6d, 0x28, 0xbe, 0x65, 0x9f,
	0x0a, 0xbf, 0x37, 0x20, 0xb0, 0x97, 0x1b, 0x55, 0xd3, 0x6d, 0x55, 0x1c, 0x9a, 0xfd, 0x39, 0xbd,
	0xdd, 0x9f, 0x0d, 0xda, 0x9f, 0xb7, 0x80, 0x18, 0x42, 0x97, 0xf6, 0x03, 0xc6, 0x09, 0x6a, 0xb6,
	0xd6, 0x85, 0xc4, 0x11, 0x4f, 0xee, 0x18, 0x2f, 0x57, 0xb1, 0x8e, 0xcb, 0xa5, 0xca, 0xc2, 0xa6,
	0xa5, 0xfd, 0x86, 0x9b, 0x5e, 0x34, 0xf8, 0x49, 0x56, 0x86, 0x81, 0x75, 0xa1, 0x06, 0x4c, 0x2f,
	0x0a, 0x66, 0xaa, 0x8c, 0x57, 0x61, 0xcb, 0xe6, 0x5d, 0x48, 0x3c, 0x01, 0xe0, 0xd6, 0xc6, 0xc6,
	0xb6, 0x25, 0x38, 0x88, 0x78, 0x0a, 0x77, 0xc9, 0xc6, 0xc9, 0x5a, 0x6b, 0xcc, 0xca, 0xf0, 0x8e,
	0xa5, 0x6c, 0x83, 0x35, 0xcb, 0x16, 0x9d, 0xe7, 0x61, 0xc7, 0x65, 0x31, 0x28, 0x7f, 0x78, 0xfc,
	0xd3, 0x49, 0x80, 0x79, 0x5f, 0xe7, 0xf4, 0xbe, 0xc8, 0x40, 0x8e, 0xcc, 0x5b, 0x74, 0xac, 0xb3,
	0x67, 0x33, 0x69, 0x92, 0xe8, 0xd3, 0xa4, 0x49, 0xdd, 0x00, 0x82, 0x0f, 0xea, 0x1a, 0xb5, 0xb5,
	0x27, 0x88, 0x28, 0x30, 0xbf, 0x9a, 0x1a, 0xcf, 0x54, 0x12, 0x6f, 0xd8, 0x15, 0x17, 0x72, 0x19,
	0x8e, 0x2f, 0x0e, 0x24, 0x7a, 0xe0, 0xbf, 0x55, 0x73, 0x36, 0xc4, 0x1c, 0x4d, 0xcd, 0xd9, 0xd5,
	0xd5, 0xe9, 0x32, 0xc3, 0xd9, 0x32, 0x45, 0xf6, 0xc1, 0x85, 0xe6, 0x2d, 0xfb, 0xa7, 0xfa, 0xf2,
	0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0x56, 0x95, 0x51, 0x73, 0x07, 0x00, 0x00,
}
