// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupCreateRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupCreateRequest) Reset()         { *m = GroupCreateRequest{} }
func (m *GroupCreateRequest) String() string { return proto.CompactTextString(m) }
func (*GroupCreateRequest) ProtoMessage()    {}
func (*GroupCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{0}
}

func (m *GroupCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupCreateRequest.Unmarshal(m, b)
}
func (m *GroupCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupCreateRequest.Marshal(b, m, deterministic)
}
func (m *GroupCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupCreateRequest.Merge(m, src)
}
func (m *GroupCreateRequest) XXX_Size() int {
	return xxx_messageInfo_GroupCreateRequest.Size(m)
}
func (m *GroupCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupCreateRequest proto.InternalMessageInfo

func (m *GroupCreateRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type GroupCreateResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Group                *Group       `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupCreateResponse) Reset()         { *m = GroupCreateResponse{} }
func (m *GroupCreateResponse) String() string { return proto.CompactTextString(m) }
func (*GroupCreateResponse) ProtoMessage()    {}
func (*GroupCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{1}
}

func (m *GroupCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupCreateResponse.Unmarshal(m, b)
}
func (m *GroupCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupCreateResponse.Marshal(b, m, deterministic)
}
func (m *GroupCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupCreateResponse.Merge(m, src)
}
func (m *GroupCreateResponse) XXX_Size() int {
	return xxx_messageInfo_GroupCreateResponse.Size(m)
}
func (m *GroupCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupCreateResponse proto.InternalMessageInfo

func (m *GroupCreateResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupCreateResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GroupCreateResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupOwnRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupOwnRequest) Reset()         { *m = GroupOwnRequest{} }
func (m *GroupOwnRequest) String() string { return proto.CompactTextString(m) }
func (*GroupOwnRequest) ProtoMessage()    {}
func (*GroupOwnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{2}
}

func (m *GroupOwnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupOwnRequest.Unmarshal(m, b)
}
func (m *GroupOwnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupOwnRequest.Marshal(b, m, deterministic)
}
func (m *GroupOwnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupOwnRequest.Merge(m, src)
}
func (m *GroupOwnRequest) XXX_Size() int {
	return xxx_messageInfo_GroupOwnRequest.Size(m)
}
func (m *GroupOwnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupOwnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupOwnRequest proto.InternalMessageInfo

type GroupOwnResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Group                *Group       `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupOwnResponse) Reset()         { *m = GroupOwnResponse{} }
func (m *GroupOwnResponse) String() string { return proto.CompactTextString(m) }
func (*GroupOwnResponse) ProtoMessage()    {}
func (*GroupOwnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{3}
}

func (m *GroupOwnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupOwnResponse.Unmarshal(m, b)
}
func (m *GroupOwnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupOwnResponse.Marshal(b, m, deterministic)
}
func (m *GroupOwnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupOwnResponse.Merge(m, src)
}
func (m *GroupOwnResponse) XXX_Size() int {
	return xxx_messageInfo_GroupOwnResponse.Size(m)
}
func (m *GroupOwnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupOwnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupOwnResponse proto.InternalMessageInfo

func (m *GroupOwnResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupOwnResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GroupOwnResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupListRequest) Reset()         { *m = GroupListRequest{} }
func (m *GroupListRequest) String() string { return proto.CompactTextString(m) }
func (*GroupListRequest) ProtoMessage()    {}
func (*GroupListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{4}
}

func (m *GroupListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupListRequest.Unmarshal(m, b)
}
func (m *GroupListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupListRequest.Marshal(b, m, deterministic)
}
func (m *GroupListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupListRequest.Merge(m, src)
}
func (m *GroupListRequest) XXX_Size() int {
	return xxx_messageInfo_GroupListRequest.Size(m)
}
func (m *GroupListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupListRequest proto.InternalMessageInfo

type GroupListResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Groups               []*Group     `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupListResponse) Reset()         { *m = GroupListResponse{} }
func (m *GroupListResponse) String() string { return proto.CompactTextString(m) }
func (*GroupListResponse) ProtoMessage()    {}
func (*GroupListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{5}
}

func (m *GroupListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupListResponse.Unmarshal(m, b)
}
func (m *GroupListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupListResponse.Marshal(b, m, deterministic)
}
func (m *GroupListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupListResponse.Merge(m, src)
}
func (m *GroupListResponse) XXX_Size() int {
	return xxx_messageInfo_GroupListResponse.Size(m)
}
func (m *GroupListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupListResponse proto.InternalMessageInfo

func (m *GroupListResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupListResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GroupListResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GroupMembersRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMembersRequest) Reset()         { *m = GroupMembersRequest{} }
func (m *GroupMembersRequest) String() string { return proto.CompactTextString(m) }
func (*GroupMembersRequest) ProtoMessage()    {}
func (*GroupMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{6}
}

func (m *GroupMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMembersRequest.Unmarshal(m, b)
}
func (m *GroupMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMembersRequest.Marshal(b, m, deterministic)
}
func (m *GroupMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMembersRequest.Merge(m, src)
}
func (m *GroupMembersRequest) XXX_Size() int {
	return xxx_messageInfo_GroupMembersRequest.Size(m)
}
func (m *GroupMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMembersRequest proto.InternalMessageInfo

func (m *GroupMembersRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type GroupMembersResponse struct {
	Code                 ResponseCode   `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error         `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Members              []*GroupMember `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GroupMembersResponse) Reset()         { *m = GroupMembersResponse{} }
func (m *GroupMembersResponse) String() string { return proto.CompactTextString(m) }
func (*GroupMembersResponse) ProtoMessage()    {}
func (*GroupMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{7}
}

func (m *GroupMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMembersResponse.Unmarshal(m, b)
}
func (m *GroupMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMembersResponse.Marshal(b, m, deterministic)
}
func (m *GroupMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMembersResponse.Merge(m, src)
}
func (m *GroupMembersResponse) XXX_Size() int {
	return xxx_messageInfo_GroupMembersResponse.Size(m)
}
func (m *GroupMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMembersResponse proto.InternalMessageInfo

func (m *GroupMembersResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupMembersResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GroupMembersResponse) GetMembers() []*GroupMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type GroupOperRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Oper                 int32    `protobuf:"varint,2,opt,name=oper,proto3" json:"oper,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupOperRequest) Reset()         { *m = GroupOperRequest{} }
func (m *GroupOperRequest) String() string { return proto.CompactTextString(m) }
func (*GroupOperRequest) ProtoMessage()    {}
func (*GroupOperRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{8}
}

func (m *GroupOperRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupOperRequest.Unmarshal(m, b)
}
func (m *GroupOperRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupOperRequest.Marshal(b, m, deterministic)
}
func (m *GroupOperRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupOperRequest.Merge(m, src)
}
func (m *GroupOperRequest) XXX_Size() int {
	return xxx_messageInfo_GroupOperRequest.Size(m)
}
func (m *GroupOperRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupOperRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupOperRequest proto.InternalMessageInfo

func (m *GroupOperRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupOperRequest) GetOper() int32 {
	if m != nil {
		return m.Oper
	}
	return 0
}

type GroupOperResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupOperResponse) Reset()         { *m = GroupOperResponse{} }
func (m *GroupOperResponse) String() string { return proto.CompactTextString(m) }
func (*GroupOperResponse) ProtoMessage()    {}
func (*GroupOperResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{9}
}

func (m *GroupOperResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupOperResponse.Unmarshal(m, b)
}
func (m *GroupOperResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupOperResponse.Marshal(b, m, deterministic)
}
func (m *GroupOperResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupOperResponse.Merge(m, src)
}
func (m *GroupOperResponse) XXX_Size() int {
	return xxx_messageInfo_GroupOperResponse.Size(m)
}
func (m *GroupOperResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupOperResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupOperResponse proto.InternalMessageInfo

func (m *GroupOperResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GroupOperResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type Group struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	GroupName            string   `protobuf:"bytes,2,opt,name=GroupName,proto3" json:"GroupName,omitempty"`
	GroupLeader          string   `protobuf:"bytes,3,opt,name=GroupLeader,proto3" json:"GroupLeader,omitempty"`
	GroupDeclaration     string   `protobuf:"bytes,4,opt,name=GroupDeclaration,proto3" json:"GroupDeclaration,omitempty"`
	MemberCnt            int32    `protobuf:"varint,5,opt,name=MemberCnt,proto3" json:"MemberCnt,omitempty"`
	MemberTotal          int32    `protobuf:"varint,6,opt,name=MemberTotal,proto3" json:"MemberTotal,omitempty"`
	GroupLevel           int32    `protobuf:"varint,7,opt,name=GroupLevel,proto3" json:"GroupLevel,omitempty"`
	ContriCurrent        int32    `protobuf:"varint,8,opt,name=ContriCurrent,proto3" json:"ContriCurrent,omitempty"`
	ContriLevelUp        int32    `protobuf:"varint,9,opt,name=ContriLevelUp,proto3" json:"ContriLevelUp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{10}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *Group) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Group) GetGroupLeader() string {
	if m != nil {
		return m.GroupLeader
	}
	return ""
}

func (m *Group) GetGroupDeclaration() string {
	if m != nil {
		return m.GroupDeclaration
	}
	return ""
}

func (m *Group) GetMemberCnt() int32 {
	if m != nil {
		return m.MemberCnt
	}
	return 0
}

func (m *Group) GetMemberTotal() int32 {
	if m != nil {
		return m.MemberTotal
	}
	return 0
}

func (m *Group) GetGroupLevel() int32 {
	if m != nil {
		return m.GroupLevel
	}
	return 0
}

func (m *Group) GetContriCurrent() int32 {
	if m != nil {
		return m.ContriCurrent
	}
	return 0
}

func (m *Group) GetContriLevelUp() int32 {
	if m != nil {
		return m.ContriLevelUp
	}
	return 0
}

type GroupMember struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	Power                int32    `protobuf:"varint,4,opt,name=Power,proto3" json:"Power,omitempty"`
	ContriToday          int32    `protobuf:"varint,5,opt,name=ContriToday,proto3" json:"ContriToday,omitempty"`
	ContriTotal          int32    `protobuf:"varint,6,opt,name=ContriTotal,proto3" json:"ContriTotal,omitempty"`
	Job                  int32    `protobuf:"varint,7,opt,name=Job,proto3" json:"Job,omitempty"`
	OffLineTime          int32    `protobuf:"varint,8,opt,name=OffLineTime,proto3" json:"OffLineTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMember) Reset()         { *m = GroupMember{} }
func (m *GroupMember) String() string { return proto.CompactTextString(m) }
func (*GroupMember) ProtoMessage()    {}
func (*GroupMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{11}
}

func (m *GroupMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMember.Unmarshal(m, b)
}
func (m *GroupMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMember.Marshal(b, m, deterministic)
}
func (m *GroupMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMember.Merge(m, src)
}
func (m *GroupMember) XXX_Size() int {
	return xxx_messageInfo_GroupMember.Size(m)
}
func (m *GroupMember) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMember.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMember proto.InternalMessageInfo

func (m *GroupMember) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GroupMember) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupMember) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GroupMember) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *GroupMember) GetContriToday() int32 {
	if m != nil {
		return m.ContriToday
	}
	return 0
}

func (m *GroupMember) GetContriTotal() int32 {
	if m != nil {
		return m.ContriTotal
	}
	return 0
}

func (m *GroupMember) GetJob() int32 {
	if m != nil {
		return m.Job
	}
	return 0
}

func (m *GroupMember) GetOffLineTime() int32 {
	if m != nil {
		return m.OffLineTime
	}
	return 0
}

func init() {
	proto.RegisterType((*GroupCreateRequest)(nil), "msg.GroupCreateRequest")
	proto.RegisterType((*GroupCreateResponse)(nil), "msg.GroupCreateResponse")
	proto.RegisterType((*GroupOwnRequest)(nil), "msg.GroupOwnRequest")
	proto.RegisterType((*GroupOwnResponse)(nil), "msg.GroupOwnResponse")
	proto.RegisterType((*GroupListRequest)(nil), "msg.GroupListRequest")
	proto.RegisterType((*GroupListResponse)(nil), "msg.GroupListResponse")
	proto.RegisterType((*GroupMembersRequest)(nil), "msg.GroupMembersRequest")
	proto.RegisterType((*GroupMembersResponse)(nil), "msg.GroupMembersResponse")
	proto.RegisterType((*GroupOperRequest)(nil), "msg.GroupOperRequest")
	proto.RegisterType((*GroupOperResponse)(nil), "msg.GroupOperResponse")
	proto.RegisterType((*Group)(nil), "msg.Group")
	proto.RegisterType((*GroupMember)(nil), "msg.GroupMember")
}

func init() { proto.RegisterFile("group.proto", fileDescriptor_e10f4c9b19ad8eee) }

var fileDescriptor_e10f4c9b19ad8eee = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0xa5, 0x4d, 0xd3, 0xda, 0x5b, 0xd4, 0x76, 0x5c, 0x64, 0x90, 0x45, 0xc2, 0xa0, 0xb0, 0xec,
	0x43, 0x85, 0xfa, 0x03, 0x42, 0x94, 0xa2, 0xac, 0xae, 0x84, 0x2e, 0xf8, 0x9a, 0x6e, 0xee, 0x96,
	0x40, 0x93, 0x89, 0x37, 0xa9, 0xcb, 0xc2, 0xbe, 0xfb, 0x4d, 0x7e, 0x8c, 0xff, 0x22, 0x73, 0x67,
	0xd2, 0x4c, 0xf5, 0xc1, 0x97, 0xb2, 0x6f, 0x73, 0xcf, 0x3d, 0x33, 0xe7, 0xcc, 0xb9, 0x99, 0xc0,
	0x64, 0x43, 0x7a, 0x57, 0xcd, 0x2b, 0xd2, 0x8d, 0x16, 0x41, 0x51, 0x6f, 0x5e, 0x8c, 0x91, 0xc8,
	0xd6, 0x6a, 0x01, 0x62, 0x69, 0xda, 0x31, 0x61, 0xda, 0x60, 0x82, 0xdf, 0x77, 0x58, 0x37, 0xe2,
	0x14, 0xc6, 0xbc, 0xe9, 0x4b, 0x5a, 0xa0, 0xec, 0x45, 0xbd, 0xb3, 0x71, 0xd2, 0x01, 0xea, 0x1e,
	0x9e, 0x1d, 0xec, 0xa9, 0x2b, 0x5d, 0xd6, 0x28, 0x5e, 0xc3, 0xe0, 0x5a, 0x67, 0x96, 0xff, 0x64,
	0x31, 0x9b, 0x17, 0xf5, 0x66, 0xde, 0x36, 0x63, 0x9d, 0x61, 0xc2, 0x6d, 0x71, 0x0a, 0x01, 0x12,
	0xc9, 0x7e, 0xd4, 0x3b, 0x9b, 0x2c, 0x80, 0x59, 0x1f, 0x88, 0x34, 0x25, 0x06, 0x16, 0x11, 0x84,
	0x2c, 0x24, 0x03, 0xaf, 0xcf, 0x6a, 0x89, 0x6d, 0xa8, 0x19, 0x3c, 0xe5, 0xfa, 0xf2, 0xb6, 0x74,
	0x76, 0xd5, 0x1d, 0x4c, 0x3b, 0xe8, 0x61, 0xdd, 0x08, 0x27, 0x7d, 0x91, 0xd7, 0x4d, 0x6b, 0xe7,
	0x1e, 0x66, 0x1e, 0x76, 0x4c, 0x3f, 0x0a, 0x86, 0x2c, 0x5b, 0xcb, 0x20, 0x0a, 0xfe, 0x32, 0xe4,
	0x3a, 0xea, 0x8d, 0x9b, 0xce, 0x67, 0x2c, 0xd6, 0x48, 0x75, 0x3b, 0x52, 0x09, 0x23, 0x26, 0x7c,
	0xcc, 0xdc, 0x40, 0xdb, 0x52, 0xfd, 0xec, 0xc1, 0xc9, 0xe1, 0x8e, 0x63, 0x5a, 0x3e, 0x87, 0x51,
	0x61, 0xcf, 0x75, 0x9e, 0xa7, 0x9d, 0x67, 0x2b, 0x98, 0xb4, 0x04, 0xf5, 0xae, 0x9d, 0x63, 0x85,
	0xf4, 0x5f, 0xdf, 0x42, 0xc0, 0x40, 0x57, 0x68, 0x85, 0xc3, 0x84, 0xd7, 0xea, 0x9b, 0x8b, 0xde,
	0x9e, 0x70, 0xc4, 0x7b, 0xa8, 0x5f, 0x7d, 0x08, 0xf9, 0x68, 0xe3, 0x68, 0x79, 0xe8, 0xc8, 0x95,
	0xe6, 0xd9, 0x2c, 0xf7, 0xcf, 0xa6, 0x6f, 0x9f, 0xcd, 0x1e, 0x10, 0x11, 0x4c, 0xec, 0x67, 0x81,
	0x69, 0x86, 0xc4, 0x9f, 0xd4, 0x38, 0xf1, 0x21, 0x71, 0xee, 0xee, 0xff, 0x1e, 0xaf, 0xb7, 0x29,
	0xa5, 0x4d, 0xae, 0x4b, 0x39, 0x60, 0xda, 0x3f, 0xb8, 0xd1, 0xb2, 0xf1, 0xc5, 0x65, 0x23, 0x43,
	0x8e, 0xa0, 0x03, 0x8c, 0x96, 0x2d, 0x56, 0xba, 0x49, 0xb7, 0x72, 0xc8, 0x7d, 0x1f, 0x12, 0x2f,
	0x01, 0x9c, 0xf4, 0x0f, 0xdc, 0xca, 0x11, 0x13, 0x3c, 0x44, 0xbc, 0x82, 0xc7, 0xb1, 0x2e, 0x1b,
	0xca, 0xe3, 0x1d, 0x11, 0x96, 0x8d, 0x7c, 0xc4, 0x94, 0x43, 0xb0, 0x63, 0xf1, 0xa6, 0xab, 0x4a,
	0x8e, 0x7d, 0x96, 0x03, 0xd5, 0xef, 0x9e, 0xbb, 0xba, 0x35, 0x20, 0x9e, 0xc3, 0xf0, 0xaa, 0x46,
	0xda, 0x07, 0xe8, 0x2a, 0x33, 0x51, 0x2f, 0x3a, 0x5e, 0x8b, 0x13, 0x08, 0xad, 0xc5, 0x80, 0x4f,
	0xb6, 0x85, 0x41, 0xbf, 0xea, 0x5b, 0x24, 0x8e, 0x27, 0x4c, 0x6c, 0x61, 0x6e, 0x6d, 0x85, 0x57,
	0x3a, 0x4b, 0xef, 0x5c, 0x2a, 0x3e, 0xe4, 0x33, 0xbc, 0x5c, 0x3c, 0x48, 0x4c, 0x21, 0xf8, 0xa4,
	0xd7, 0x2e, 0x10, 0xb3, 0x34, 0x7b, 0x2e, 0x6f, 0x6e, 0x2e, 0xf2, 0x12, 0x57, 0x79, 0x81, 0x2e,
	0x07, 0x1f, 0x5a, 0x0f, 0xf9, 0x5f, 0xfa, 0xf6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0x93,
	0x07, 0x40, 0x6a, 0x05, 0x00, 0x00,
}
