// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hero.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HeroRandomLevel int32

const (
	HeroRandomLevel_GOOD   HeroRandomLevel = 0
	HeroRandomLevel_BETTER HeroRandomLevel = 1
	HeroRandomLevel_BEST   HeroRandomLevel = 2
)

var HeroRandomLevel_name = map[int32]string{
	0: "GOOD",
	1: "BETTER",
	2: "BEST",
}

var HeroRandomLevel_value = map[string]int32{
	"GOOD":   0,
	"BETTER": 1,
	"BEST":   2,
}

func (x HeroRandomLevel) String() string {
	return proto.EnumName(HeroRandomLevel_name, int32(x))
}

func (HeroRandomLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{0}
}

type HeroRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeroRequest) Reset()         { *m = HeroRequest{} }
func (m *HeroRequest) String() string { return proto.CompactTextString(m) }
func (*HeroRequest) ProtoMessage()    {}
func (*HeroRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{0}
}

func (m *HeroRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroRequest.Unmarshal(m, b)
}
func (m *HeroRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroRequest.Marshal(b, m, deterministic)
}
func (m *HeroRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroRequest.Merge(m, src)
}
func (m *HeroRequest) XXX_Size() int {
	return xxx_messageInfo_HeroRequest.Size(m)
}
func (m *HeroRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeroRequest proto.InternalMessageInfo

type HeroResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Heros                []*Hero      `protobuf:"bytes,3,rep,name=heros,proto3" json:"heros,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HeroResponse) Reset()         { *m = HeroResponse{} }
func (m *HeroResponse) String() string { return proto.CompactTextString(m) }
func (*HeroResponse) ProtoMessage()    {}
func (*HeroResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{1}
}

func (m *HeroResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroResponse.Unmarshal(m, b)
}
func (m *HeroResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroResponse.Marshal(b, m, deterministic)
}
func (m *HeroResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroResponse.Merge(m, src)
}
func (m *HeroResponse) XXX_Size() int {
	return xxx_messageInfo_HeroResponse.Size(m)
}
func (m *HeroResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeroResponse proto.InternalMessageInfo

func (m *HeroResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *HeroResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *HeroResponse) GetHeros() []*Hero {
	if m != nil {
		return m.Heros
	}
	return nil
}

type HeroRandomRequest struct {
	Level                HeroRandomLevel `protobuf:"varint,1,opt,name=Level,proto3,enum=msg.HeroRandomLevel" json:"Level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HeroRandomRequest) Reset()         { *m = HeroRandomRequest{} }
func (m *HeroRandomRequest) String() string { return proto.CompactTextString(m) }
func (*HeroRandomRequest) ProtoMessage()    {}
func (*HeroRandomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{2}
}

func (m *HeroRandomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroRandomRequest.Unmarshal(m, b)
}
func (m *HeroRandomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroRandomRequest.Marshal(b, m, deterministic)
}
func (m *HeroRandomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroRandomRequest.Merge(m, src)
}
func (m *HeroRandomRequest) XXX_Size() int {
	return xxx_messageInfo_HeroRandomRequest.Size(m)
}
func (m *HeroRandomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroRandomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeroRandomRequest proto.InternalMessageInfo

func (m *HeroRandomRequest) GetLevel() HeroRandomLevel {
	if m != nil {
		return m.Level
	}
	return HeroRandomLevel_GOOD
}

type HeroRandomResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HeroRandomResponse) Reset()         { *m = HeroRandomResponse{} }
func (m *HeroRandomResponse) String() string { return proto.CompactTextString(m) }
func (*HeroRandomResponse) ProtoMessage()    {}
func (*HeroRandomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{3}
}

func (m *HeroRandomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroRandomResponse.Unmarshal(m, b)
}
func (m *HeroRandomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroRandomResponse.Marshal(b, m, deterministic)
}
func (m *HeroRandomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroRandomResponse.Merge(m, src)
}
func (m *HeroRandomResponse) XXX_Size() int {
	return xxx_messageInfo_HeroRandomResponse.Size(m)
}
func (m *HeroRandomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroRandomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeroRandomResponse proto.InternalMessageInfo

func (m *HeroRandomResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *HeroRandomResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type HeroOwnRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeroOwnRequest) Reset()         { *m = HeroOwnRequest{} }
func (m *HeroOwnRequest) String() string { return proto.CompactTextString(m) }
func (*HeroOwnRequest) ProtoMessage()    {}
func (*HeroOwnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{4}
}

func (m *HeroOwnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroOwnRequest.Unmarshal(m, b)
}
func (m *HeroOwnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroOwnRequest.Marshal(b, m, deterministic)
}
func (m *HeroOwnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroOwnRequest.Merge(m, src)
}
func (m *HeroOwnRequest) XXX_Size() int {
	return xxx_messageInfo_HeroOwnRequest.Size(m)
}
func (m *HeroOwnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroOwnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeroOwnRequest proto.InternalMessageInfo

type HeroOwnResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Heros                []*Hero      `protobuf:"bytes,3,rep,name=heros,proto3" json:"heros,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HeroOwnResponse) Reset()         { *m = HeroOwnResponse{} }
func (m *HeroOwnResponse) String() string { return proto.CompactTextString(m) }
func (*HeroOwnResponse) ProtoMessage()    {}
func (*HeroOwnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{5}
}

func (m *HeroOwnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroOwnResponse.Unmarshal(m, b)
}
func (m *HeroOwnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroOwnResponse.Marshal(b, m, deterministic)
}
func (m *HeroOwnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroOwnResponse.Merge(m, src)
}
func (m *HeroOwnResponse) XXX_Size() int {
	return xxx_messageInfo_HeroOwnResponse.Size(m)
}
func (m *HeroOwnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroOwnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeroOwnResponse proto.InternalMessageInfo

func (m *HeroOwnResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *HeroOwnResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *HeroOwnResponse) GetHeros() []*Hero {
	if m != nil {
		return m.Heros
	}
	return nil
}

type HeroSelectRequest struct {
	HeroId               string   `protobuf:"bytes,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	Pos                  int32    `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeroSelectRequest) Reset()         { *m = HeroSelectRequest{} }
func (m *HeroSelectRequest) String() string { return proto.CompactTextString(m) }
func (*HeroSelectRequest) ProtoMessage()    {}
func (*HeroSelectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{6}
}

func (m *HeroSelectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroSelectRequest.Unmarshal(m, b)
}
func (m *HeroSelectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroSelectRequest.Marshal(b, m, deterministic)
}
func (m *HeroSelectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroSelectRequest.Merge(m, src)
}
func (m *HeroSelectRequest) XXX_Size() int {
	return xxx_messageInfo_HeroSelectRequest.Size(m)
}
func (m *HeroSelectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroSelectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeroSelectRequest proto.InternalMessageInfo

func (m *HeroSelectRequest) GetHeroId() string {
	if m != nil {
		return m.HeroId
	}
	return ""
}

func (m *HeroSelectRequest) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

type HeroSelectResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	HeroIds              []string     `protobuf:"bytes,3,rep,name=heroIds,proto3" json:"heroIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HeroSelectResponse) Reset()         { *m = HeroSelectResponse{} }
func (m *HeroSelectResponse) String() string { return proto.CompactTextString(m) }
func (*HeroSelectResponse) ProtoMessage()    {}
func (*HeroSelectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{7}
}

func (m *HeroSelectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroSelectResponse.Unmarshal(m, b)
}
func (m *HeroSelectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroSelectResponse.Marshal(b, m, deterministic)
}
func (m *HeroSelectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroSelectResponse.Merge(m, src)
}
func (m *HeroSelectResponse) XXX_Size() int {
	return xxx_messageInfo_HeroSelectResponse.Size(m)
}
func (m *HeroSelectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroSelectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeroSelectResponse proto.InternalMessageInfo

func (m *HeroSelectResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *HeroSelectResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *HeroSelectResponse) GetHeroIds() []string {
	if m != nil {
		return m.HeroIds
	}
	return nil
}

type HeroUnSelectRequest struct {
	HeroId               string   `protobuf:"bytes,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeroUnSelectRequest) Reset()         { *m = HeroUnSelectRequest{} }
func (m *HeroUnSelectRequest) String() string { return proto.CompactTextString(m) }
func (*HeroUnSelectRequest) ProtoMessage()    {}
func (*HeroUnSelectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{8}
}

func (m *HeroUnSelectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroUnSelectRequest.Unmarshal(m, b)
}
func (m *HeroUnSelectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroUnSelectRequest.Marshal(b, m, deterministic)
}
func (m *HeroUnSelectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroUnSelectRequest.Merge(m, src)
}
func (m *HeroUnSelectRequest) XXX_Size() int {
	return xxx_messageInfo_HeroUnSelectRequest.Size(m)
}
func (m *HeroUnSelectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroUnSelectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeroUnSelectRequest proto.InternalMessageInfo

func (m *HeroUnSelectRequest) GetHeroId() string {
	if m != nil {
		return m.HeroId
	}
	return ""
}

type HeroUnSelectResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	HeroIds              []string     `protobuf:"bytes,3,rep,name=heroIds,proto3" json:"heroIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HeroUnSelectResponse) Reset()         { *m = HeroUnSelectResponse{} }
func (m *HeroUnSelectResponse) String() string { return proto.CompactTextString(m) }
func (*HeroUnSelectResponse) ProtoMessage()    {}
func (*HeroUnSelectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{9}
}

func (m *HeroUnSelectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroUnSelectResponse.Unmarshal(m, b)
}
func (m *HeroUnSelectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroUnSelectResponse.Marshal(b, m, deterministic)
}
func (m *HeroUnSelectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroUnSelectResponse.Merge(m, src)
}
func (m *HeroUnSelectResponse) XXX_Size() int {
	return xxx_messageInfo_HeroUnSelectResponse.Size(m)
}
func (m *HeroUnSelectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroUnSelectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeroUnSelectResponse proto.InternalMessageInfo

func (m *HeroUnSelectResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *HeroUnSelectResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *HeroUnSelectResponse) GetHeroIds() []string {
	if m != nil {
		return m.HeroIds
	}
	return nil
}

type HeroSkillsRequest struct {
	HeroId               string   `protobuf:"bytes,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeroSkillsRequest) Reset()         { *m = HeroSkillsRequest{} }
func (m *HeroSkillsRequest) String() string { return proto.CompactTextString(m) }
func (*HeroSkillsRequest) ProtoMessage()    {}
func (*HeroSkillsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{10}
}

func (m *HeroSkillsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroSkillsRequest.Unmarshal(m, b)
}
func (m *HeroSkillsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroSkillsRequest.Marshal(b, m, deterministic)
}
func (m *HeroSkillsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroSkillsRequest.Merge(m, src)
}
func (m *HeroSkillsRequest) XXX_Size() int {
	return xxx_messageInfo_HeroSkillsRequest.Size(m)
}
func (m *HeroSkillsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroSkillsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeroSkillsRequest proto.InternalMessageInfo

func (m *HeroSkillsRequest) GetHeroId() string {
	if m != nil {
		return m.HeroId
	}
	return ""
}

type HeroSkillsResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Skills               []*Skill     `protobuf:"bytes,3,rep,name=skills,proto3" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HeroSkillsResponse) Reset()         { *m = HeroSkillsResponse{} }
func (m *HeroSkillsResponse) String() string { return proto.CompactTextString(m) }
func (*HeroSkillsResponse) ProtoMessage()    {}
func (*HeroSkillsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{11}
}

func (m *HeroSkillsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroSkillsResponse.Unmarshal(m, b)
}
func (m *HeroSkillsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroSkillsResponse.Marshal(b, m, deterministic)
}
func (m *HeroSkillsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroSkillsResponse.Merge(m, src)
}
func (m *HeroSkillsResponse) XXX_Size() int {
	return xxx_messageInfo_HeroSkillsResponse.Size(m)
}
func (m *HeroSkillsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroSkillsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeroSkillsResponse proto.InternalMessageInfo

func (m *HeroSkillsResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *HeroSkillsResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *HeroSkillsResponse) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

type HeroItemsRequest struct {
	HeroId               string   `protobuf:"bytes,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeroItemsRequest) Reset()         { *m = HeroItemsRequest{} }
func (m *HeroItemsRequest) String() string { return proto.CompactTextString(m) }
func (*HeroItemsRequest) ProtoMessage()    {}
func (*HeroItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{12}
}

func (m *HeroItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroItemsRequest.Unmarshal(m, b)
}
func (m *HeroItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroItemsRequest.Marshal(b, m, deterministic)
}
func (m *HeroItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroItemsRequest.Merge(m, src)
}
func (m *HeroItemsRequest) XXX_Size() int {
	return xxx_messageInfo_HeroItemsRequest.Size(m)
}
func (m *HeroItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeroItemsRequest proto.InternalMessageInfo

func (m *HeroItemsRequest) GetHeroId() string {
	if m != nil {
		return m.HeroId
	}
	return ""
}

type HeroItemsResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Items                []*Item      `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HeroItemsResponse) Reset()         { *m = HeroItemsResponse{} }
func (m *HeroItemsResponse) String() string { return proto.CompactTextString(m) }
func (*HeroItemsResponse) ProtoMessage()    {}
func (*HeroItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{13}
}

func (m *HeroItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroItemsResponse.Unmarshal(m, b)
}
func (m *HeroItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroItemsResponse.Marshal(b, m, deterministic)
}
func (m *HeroItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroItemsResponse.Merge(m, src)
}
func (m *HeroItemsResponse) XXX_Size() int {
	return xxx_messageInfo_HeroItemsResponse.Size(m)
}
func (m *HeroItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeroItemsResponse proto.InternalMessageInfo

func (m *HeroItemsResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *HeroItemsResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *HeroItemsResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Hero struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	Strength             int32    `protobuf:"varint,4,opt,name=Strength,proto3" json:"Strength,omitempty"`
	Agility              int32    `protobuf:"varint,5,opt,name=Agility,proto3" json:"Agility,omitempty"`
	Intelligence         int32    `protobuf:"varint,6,opt,name=Intelligence,proto3" json:"Intelligence,omitempty"`
	Armor                int32    `protobuf:"varint,7,opt,name=Armor,proto3" json:"Armor,omitempty"`
	AttackMin            int32    `protobuf:"varint,8,opt,name=AttackMin,proto3" json:"AttackMin,omitempty"`
	AttackMax            int32    `protobuf:"varint,9,opt,name=AttackMax,proto3" json:"AttackMax,omitempty"`
	Blood                int32    `protobuf:"varint,10,opt,name=Blood,proto3" json:"Blood,omitempty"`
	Type                 int32    `protobuf:"varint,11,opt,name=Type,proto3" json:"Type,omitempty"`
	StrengthStep         int32    `protobuf:"varint,12,opt,name=StrengthStep,proto3" json:"StrengthStep,omitempty"`
	AgilityStep          int32    `protobuf:"varint,13,opt,name=AgilityStep,proto3" json:"AgilityStep,omitempty"`
	IntelligenceStep     int32    `protobuf:"varint,14,opt,name=IntelligenceStep,proto3" json:"IntelligenceStep,omitempty"`
	SkillIds             []string `protobuf:"bytes,15,rep,name=SkillIds,proto3" json:"SkillIds,omitempty"`
	HeroId               string   `protobuf:"bytes,16,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	PlayerId             string   `protobuf:"bytes,17,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	IsSelect             bool     `protobuf:"varint,18,opt,name=IsSelect,proto3" json:"IsSelect,omitempty"`
	Pos                  int32    `protobuf:"varint,19,opt,name=Pos,proto3" json:"Pos,omitempty"`
	MP                   int32    `protobuf:"varint,20,opt,name=MP,proto3" json:"MP,omitempty"`
	MaxBlood             int32    `protobuf:"varint,21,opt,name=MaxBlood,proto3" json:"MaxBlood,omitempty"`
	MaxMP                int32    `protobuf:"varint,22,opt,name=MaxMP,proto3" json:"MaxMP,omitempty"`
	SkillPoint           int32    `protobuf:"varint,23,opt,name=SkillPoint,proto3" json:"SkillPoint,omitempty"`
	Exp                  int32    `protobuf:"varint,24,opt,name=Exp,proto3" json:"Exp,omitempty"`
	LevelUpExp           int32    `protobuf:"varint,25,opt,name=LevelUpExp,proto3" json:"LevelUpExp,omitempty"`
	ItemIds              []string `protobuf:"bytes,26,rep,name=ItemIds,proto3" json:"ItemIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hero) Reset()         { *m = Hero{} }
func (m *Hero) String() string { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()    {}
func (*Hero) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{14}
}

func (m *Hero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hero.Unmarshal(m, b)
}
func (m *Hero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hero.Marshal(b, m, deterministic)
}
func (m *Hero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hero.Merge(m, src)
}
func (m *Hero) XXX_Size() int {
	return xxx_messageInfo_Hero.Size(m)
}
func (m *Hero) XXX_DiscardUnknown() {
	xxx_messageInfo_Hero.DiscardUnknown(m)
}

var xxx_messageInfo_Hero proto.InternalMessageInfo

func (m *Hero) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Hero) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hero) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Hero) GetStrength() int32 {
	if m != nil {
		return m.Strength
	}
	return 0
}

func (m *Hero) GetAgility() int32 {
	if m != nil {
		return m.Agility
	}
	return 0
}

func (m *Hero) GetIntelligence() int32 {
	if m != nil {
		return m.Intelligence
	}
	return 0
}

func (m *Hero) GetArmor() int32 {
	if m != nil {
		return m.Armor
	}
	return 0
}

func (m *Hero) GetAttackMin() int32 {
	if m != nil {
		return m.AttackMin
	}
	return 0
}

func (m *Hero) GetAttackMax() int32 {
	if m != nil {
		return m.AttackMax
	}
	return 0
}

func (m *Hero) GetBlood() int32 {
	if m != nil {
		return m.Blood
	}
	return 0
}

func (m *Hero) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Hero) GetStrengthStep() int32 {
	if m != nil {
		return m.StrengthStep
	}
	return 0
}

func (m *Hero) GetAgilityStep() int32 {
	if m != nil {
		return m.AgilityStep
	}
	return 0
}

func (m *Hero) GetIntelligenceStep() int32 {
	if m != nil {
		return m.IntelligenceStep
	}
	return 0
}

func (m *Hero) GetSkillIds() []string {
	if m != nil {
		return m.SkillIds
	}
	return nil
}

func (m *Hero) GetHeroId() string {
	if m != nil {
		return m.HeroId
	}
	return ""
}

func (m *Hero) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *Hero) GetIsSelect() bool {
	if m != nil {
		return m.IsSelect
	}
	return false
}

func (m *Hero) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *Hero) GetMP() int32 {
	if m != nil {
		return m.MP
	}
	return 0
}

func (m *Hero) GetMaxBlood() int32 {
	if m != nil {
		return m.MaxBlood
	}
	return 0
}

func (m *Hero) GetMaxMP() int32 {
	if m != nil {
		return m.MaxMP
	}
	return 0
}

func (m *Hero) GetSkillPoint() int32 {
	if m != nil {
		return m.SkillPoint
	}
	return 0
}

func (m *Hero) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Hero) GetLevelUpExp() int32 {
	if m != nil {
		return m.LevelUpExp
	}
	return 0
}

func (m *Hero) GetItemIds() []string {
	if m != nil {
		return m.ItemIds
	}
	return nil
}

func init() {
	proto.RegisterEnum("msg.HeroRandomLevel", HeroRandomLevel_name, HeroRandomLevel_value)
	proto.RegisterType((*HeroRequest)(nil), "msg.HeroRequest")
	proto.RegisterType((*HeroResponse)(nil), "msg.HeroResponse")
	proto.RegisterType((*HeroRandomRequest)(nil), "msg.HeroRandomRequest")
	proto.RegisterType((*HeroRandomResponse)(nil), "msg.HeroRandomResponse")
	proto.RegisterType((*HeroOwnRequest)(nil), "msg.HeroOwnRequest")
	proto.RegisterType((*HeroOwnResponse)(nil), "msg.HeroOwnResponse")
	proto.RegisterType((*HeroSelectRequest)(nil), "msg.HeroSelectRequest")
	proto.RegisterType((*HeroSelectResponse)(nil), "msg.HeroSelectResponse")
	proto.RegisterType((*HeroUnSelectRequest)(nil), "msg.HeroUnSelectRequest")
	proto.RegisterType((*HeroUnSelectResponse)(nil), "msg.HeroUnSelectResponse")
	proto.RegisterType((*HeroSkillsRequest)(nil), "msg.HeroSkillsRequest")
	proto.RegisterType((*HeroSkillsResponse)(nil), "msg.HeroSkillsResponse")
	proto.RegisterType((*HeroItemsRequest)(nil), "msg.HeroItemsRequest")
	proto.RegisterType((*HeroItemsResponse)(nil), "msg.HeroItemsResponse")
	proto.RegisterType((*Hero)(nil), "msg.Hero")
}

func init() { proto.RegisterFile("hero.proto", fileDescriptor_d5c1be3f86b99613) }

var fileDescriptor_d5c1be3f86b99613 = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcf, 0x6f, 0xda, 0x4a,
	0x10, 0x7e, 0xfc, 0x0c, 0x0c, 0x09, 0x71, 0x36, 0xbc, 0xbc, 0x7d, 0x28, 0x7a, 0x0f, 0x59, 0xaa,
	0x84, 0xa8, 0x1a, 0xa9, 0xe9, 0xb9, 0xaa, 0x92, 0x16, 0x35, 0x48, 0xa5, 0x41, 0x86, 0x1c, 0x7a,
	0x74, 0x61, 0x45, 0xac, 0xd8, 0x5e, 0x77, 0xbd, 0x69, 0xe0, 0xd0, 0xff, 0xaa, 0x7f, 0x60, 0x35,
	0x33, 0x36, 0x31, 0xea, 0x21, 0x3d, 0xa0, 0xdc, 0xfc, 0xcd, 0x37, 0xb3, 0xdf, 0xb7, 0xb3, 0xb3,
	0x6b, 0x80, 0x5b, 0x65, 0xf4, 0x59, 0x62, 0xb4, 0xd5, 0xa2, 0x12, 0xa5, 0xcb, 0x6e, 0x53, 0x19,
	0xc3, 0xb8, 0xdb, 0x4a, 0xef, 0x82, 0x30, 0xcc, 0x00, 0x04, 0x56, 0x45, 0xfc, 0xed, 0x1e, 0x40,
	0xeb, 0x4a, 0x19, 0xed, 0xa9, 0x6f, 0xf7, 0x2a, 0xb5, 0xae, 0x85, 0x7d, 0x86, 0x69, 0xa2, 0xe3,
	0x54, 0x89, 0x17, 0x50, 0x9d, 0xeb, 0x85, 0x92, 0xa5, 0x5e, 0xa9, 0xdf, 0x3e, 0x3f, 0x3a, 0x8b,
	0xd2, 0xe5, 0x59, 0x4e, 0xbe, 0xd7, 0x0b, 0xe5, 0x11, 0x2d, 0x4e, 0xa1, 0xa2, 0x8c, 0x91, 0xe5,
	0x5e, 0xa9, 0xdf, 0x3a, 0x07, 0xca, 0x1a, 0x1a, 0xa3, 0x8d, 0x87, 0x61, 0xf1, 0x3f, 0xd4, 0xd0,
	0x5a, 0x2a, 0x2b, 0xbd, 0x4a, 0xbf, 0x75, 0xde, 0x24, 0x9e, 0x64, 0x38, 0xee, 0xbe, 0x83, 0x23,
	0x82, 0x7e, 0xbc, 0xd0, 0x51, 0x66, 0x45, 0x0c, 0xa0, 0xf6, 0x49, 0x7d, 0x57, 0x61, 0xa6, 0xdd,
	0x79, 0xac, 0xa2, 0x34, 0xe2, 0x3c, 0x4e, 0x71, 0xbf, 0x80, 0x28, 0x2e, 0xb0, 0x43, 0xf3, 0xae,
	0x03, 0x6d, 0x5c, 0xfa, 0xfa, 0x21, 0xce, 0x7b, 0xf4, 0x00, 0x87, 0x9b, 0xc8, 0xb3, 0xb6, 0xe9,
	0x2d, 0xb7, 0x69, 0xaa, 0x42, 0x35, 0xb7, 0x79, 0x9b, 0x4e, 0xa0, 0x8e, 0xec, 0x68, 0x41, 0xe2,
	0x4d, 0x2f, 0x43, 0xc2, 0x81, 0x4a, 0xa2, 0x53, 0xd2, 0xaa, 0x79, 0xf8, 0xe9, 0xa6, 0xdc, 0xa4,
	0xbc, 0x7c, 0x97, 0xd6, 0x25, 0xec, 0xb1, 0x2c, 0x9b, 0x6f, 0x7a, 0x39, 0x74, 0x5f, 0xc1, 0x31,
	0x8a, 0xde, 0xc4, 0x7f, 0xe4, 0xda, 0xbd, 0x87, 0xce, 0x76, 0xfa, 0xf3, 0xb8, 0x7c, 0x99, 0x75,
	0x16, 0x2f, 0x49, 0xfa, 0x94, 0xc7, 0x1f, 0x59, 0x1f, 0xb3, 0xe4, 0x5d, 0x3a, 0x74, 0xa1, 0x4e,
	0x17, 0x35, 0x9f, 0x01, 0x4e, 0x20, 0x25, 0x2f, 0x63, 0xdc, 0x01, 0x38, 0x28, 0x3f, 0xb2, 0x2a,
	0x7a, 0xd2, 0xea, 0x9a, 0xf7, 0x95, 0xe5, 0xee, 0x78, 0x58, 0xf1, 0x15, 0xd9, 0x1e, 0x56, 0xd4,
	0xf1, 0x38, 0xee, 0xfe, 0xac, 0x41, 0x15, 0xb5, 0x45, 0x1b, 0xca, 0x99, 0xaf, 0x9a, 0x57, 0x1e,
	0x2d, 0x84, 0x80, 0xea, 0x67, 0x3f, 0x52, 0xb4, 0x70, 0xd3, 0xa3, 0x6f, 0xd1, 0xc9, 0xef, 0x7a,
	0x85, 0xd2, 0x18, 0x88, 0x2e, 0x34, 0xa6, 0xd6, 0xa8, 0x78, 0x69, 0x6f, 0x65, 0x95, 0x88, 0x0d,
	0xc6, 0xb3, 0xbc, 0x58, 0x06, 0x61, 0x60, 0xd7, 0xb2, 0x46, 0x54, 0x0e, 0x85, 0x0b, 0xfb, 0xa3,
	0xd8, 0xaa, 0x30, 0x0c, 0x96, 0x2a, 0x9e, 0x2b, 0x59, 0x27, 0x7a, 0x2b, 0x86, 0x7a, 0x17, 0x26,
	0xd2, 0x46, 0xee, 0xb1, 0x1e, 0x01, 0x71, 0x0a, 0xcd, 0x0b, 0x6b, 0xfd, 0xf9, 0xdd, 0x38, 0x88,
	0x65, 0x83, 0x98, 0xc7, 0x40, 0x81, 0xf5, 0x57, 0xb2, 0xb9, 0xc5, 0xfa, 0x2b, 0x5c, 0xf1, 0x32,
	0xd4, 0x7a, 0x21, 0x81, 0x57, 0x24, 0x80, 0x7b, 0x9d, 0xad, 0x13, 0x25, 0x5b, 0x14, 0xa4, 0x6f,
	0xf4, 0x97, 0xef, 0x62, 0x6a, 0x55, 0x22, 0xf7, 0xd9, 0x5f, 0x31, 0x26, 0x7a, 0xd0, 0xca, 0xb6,
	0x43, 0x29, 0x07, 0x94, 0x52, 0x0c, 0x89, 0x01, 0x38, 0xc5, 0x1d, 0x51, 0x5a, 0x9b, 0xd2, 0x7e,
	0x8b, 0x53, 0x1f, 0x71, 0x76, 0x70, 0xf0, 0x0f, 0x69, 0xf0, 0x37, 0x18, 0x27, 0xe7, 0x8a, 0x27,
	0xc7, 0xe1, 0xc9, 0x61, 0x84, 0x35, 0x93, 0xd0, 0x5f, 0x2b, 0x33, 0x5a, 0xc8, 0x23, 0x62, 0x36,
	0x18, 0xb9, 0x51, 0xca, 0x17, 0x54, 0x8a, 0x5e, 0xa9, 0xdf, 0xf0, 0x36, 0x18, 0x9f, 0x9d, 0x89,
	0x4e, 0xe5, 0x31, 0x3f, 0x3b, 0x13, 0x9d, 0xe2, 0xf9, 0x8f, 0x27, 0xb2, 0xc3, 0xe7, 0x3f, 0x9e,
	0x60, 0xf5, 0xd8, 0x5f, 0x71, 0xb3, 0xfe, 0xe6, 0x53, 0xcd, 0x31, 0x76, 0x71, 0xec, 0xaf, 0xc6,
	0x13, 0x79, 0xc2, 0x5d, 0x24, 0x20, 0xfe, 0x03, 0x20, 0xbf, 0x13, 0x1d, 0xc4, 0x56, 0xfe, 0x43,
	0x54, 0x21, 0x82, 0x9a, 0xc3, 0x55, 0x22, 0x25, 0x6b, 0x0e, 0x57, 0x09, 0x56, 0xd0, 0x08, 0xdd,
	0x24, 0x48, 0xfc, 0xcb, 0x15, 0x8f, 0x11, 0x9c, 0x1e, 0x9c, 0x55, 0x6c, 0x48, 0x97, 0x5f, 0x82,
	0x0c, 0x0e, 0x5e, 0xf3, 0xe3, 0x5e, 0xf8, 0xc7, 0x88, 0x06, 0x54, 0x3f, 0x5e, 0x5f, 0x7f, 0x70,
	0xfe, 0x12, 0x00, 0xf5, 0xcb, 0xe1, 0x6c, 0x36, 0xf4, 0x9c, 0x12, 0x46, 0x2f, 0x87, 0xd3, 0x99,
	0x53, 0xfe, 0x5a, 0xa7, 0x3f, 0xe9, 0x9b, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x39, 0xce,
	0xbd, 0x80, 0x07, 0x00, 0x00,
}
