// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemRequest) Reset()         { *m = ItemRequest{} }
func (m *ItemRequest) String() string { return proto.CompactTextString(m) }
func (*ItemRequest) ProtoMessage()    {}
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *ItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemRequest.Unmarshal(m, b)
}
func (m *ItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemRequest.Marshal(b, m, deterministic)
}
func (m *ItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemRequest.Merge(m, src)
}
func (m *ItemRequest) XXX_Size() int {
	return xxx_messageInfo_ItemRequest.Size(m)
}
func (m *ItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemRequest proto.InternalMessageInfo

type ItemResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Items                []*Item      `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ItemResponse) Reset()         { *m = ItemResponse{} }
func (m *ItemResponse) String() string { return proto.CompactTextString(m) }
func (*ItemResponse) ProtoMessage()    {}
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *ItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemResponse.Unmarshal(m, b)
}
func (m *ItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemResponse.Marshal(b, m, deterministic)
}
func (m *ItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemResponse.Merge(m, src)
}
func (m *ItemResponse) XXX_Size() int {
	return xxx_messageInfo_ItemResponse.Size(m)
}
func (m *ItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemResponse proto.InternalMessageInfo

func (m *ItemResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *ItemResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *ItemResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"`
	Effect               string   `protobuf:"bytes,4,opt,name=Effect,proto3" json:"Effect,omitempty"`
	Desc                 string   `protobuf:"bytes,5,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Mixs                 []*Mix   `protobuf:"bytes,6,rep,name=Mixs,proto3" json:"Mixs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *Item) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Item) GetMixs() []*Mix {
	if m != nil {
		return m.Mixs
	}
	return nil
}

type Mix struct {
	ItemId               int32    `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	Num                  int32    `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mix) Reset()         { *m = Mix{} }
func (m *Mix) String() string { return proto.CompactTextString(m) }
func (*Mix) ProtoMessage()    {}
func (*Mix) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{3}
}

func (m *Mix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mix.Unmarshal(m, b)
}
func (m *Mix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mix.Marshal(b, m, deterministic)
}
func (m *Mix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mix.Merge(m, src)
}
func (m *Mix) XXX_Size() int {
	return xxx_messageInfo_Mix.Size(m)
}
func (m *Mix) XXX_DiscardUnknown() {
	xxx_messageInfo_Mix.DiscardUnknown(m)
}

var xxx_messageInfo_Mix proto.InternalMessageInfo

func (m *Mix) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Mix) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*ItemRequest)(nil), "msg.ItemRequest")
	proto.RegisterType((*ItemResponse)(nil), "msg.ItemResponse")
	proto.RegisterType((*Item)(nil), "msg.Item")
	proto.RegisterType((*Mix)(nil), "msg.Mix")
}

func init() { proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df) }

var fileDescriptor_6007f868cf6553df = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xd1, 0x4a, 0xec, 0x30,
	0x10, 0x86, 0x69, 0xd3, 0x96, 0xd3, 0xe9, 0x71, 0xd1, 0x41, 0x24, 0xc8, 0x82, 0xa5, 0x20, 0xf4,
	0xaa, 0x42, 0x7d, 0x04, 0xdd, 0x8b, 0x5e, 0x74, 0x91, 0xbc, 0x81, 0xb6, 0xb3, 0x4b, 0x2f, 0x62,
	0xd6, 0x24, 0x0b, 0x7d, 0x06, 0x9f, 0x5a, 0x32, 0x59, 0xbd, 0x9b, 0x6f, 0xe6, 0xe7, 0xcf, 0x47,
	0x00, 0x16, 0x4f, 0xba, 0x3b, 0x59, 0xe3, 0x0d, 0x0a, 0xed, 0x8e, 0xf7, 0x25, 0x59, 0x1b, 0xb9,
	0xb9, 0x82, 0x6a, 0xf0, 0xa4, 0x15, 0x7d, 0x9d, 0xc9, 0xf9, 0xc6, 0xc3, 0xff, 0x88, 0xee, 0x64,
	0x3e, 0x1d, 0xe1, 0x23, 0x64, 0x93, 0x99, 0x49, 0x26, 0x75, 0xd2, 0x6e, 0xfa, 0x9b, 0x4e, 0xbb,
	0x63, 0xf7, 0x7b, 0x7c, 0x31, 0x33, 0x29, 0x3e, 0xe3, 0x16, 0x04, 0x59, 0x2b, 0xd3, 0x3a, 0x69,
	0xab, 0x1e, 0x38, 0xb5, 0xb3, 0xd6, 0x58, 0x15, 0xd6, 0xf8, 0x00, 0x79, 0x30, 0x70, 0x52, 0xd4,
	0xa2, 0xad, 0xfa, 0x92, 0xef, 0xfc, 0x4c, 0xdc, 0x37, 0xdf, 0x09, 0x64, 0x81, 0x71, 0x03, 0xe9,
	0x30, 0xf3, 0x63, 0xb9, 0x4a, 0x87, 0x19, 0x11, 0xb2, 0xfd, 0xbb, 0x26, 0x2e, 0x2e, 0x15, 0xcf,
	0x78, 0x0b, 0xf9, 0x9b, 0x5d, 0x26, 0x92, 0x82, 0x63, 0x11, 0xf0, 0x0e, 0x8a, 0xdd, 0xe1, 0x40,
	0x93, 0x97, 0x19, 0x67, 0x2f, 0x14, 0x1a, 0x5e, 0xc9, 0x4d, 0x32, 0x8f, 0x0d, 0x61, 0xc6, 0x2d,
	0x64, 0xe3, 0xb2, 0x3a, 0x59, 0xb0, 0xce, 0x3f, 0xd6, 0x19, 0x97, 0x55, 0xf1, 0xb6, 0x79, 0x02,
	0x31, 0x2e, 0x6b, 0x28, 0x0c, 0x4a, 0x7f, 0x3a, 0x17, 0xc2, 0x6b, 0x10, 0xfb, 0xb3, 0x66, 0xa3,
	0x5c, 0x85, 0xf1, 0xa3, 0xe0, 0x9f, 0x7c, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x25, 0xe6, 0x68,
	0x27, 0x67, 0x01, 0x00, 0x00,
}
