// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 登录
type LoginRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Player               *Player      `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *LoginResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *LoginResponse) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

// 注册
type RegisteRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisteRequest) Reset()         { *m = RegisteRequest{} }
func (m *RegisteRequest) String() string { return proto.CompactTextString(m) }
func (*RegisteRequest) ProtoMessage()    {}
func (*RegisteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *RegisteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteRequest.Unmarshal(m, b)
}
func (m *RegisteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteRequest.Marshal(b, m, deterministic)
}
func (m *RegisteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteRequest.Merge(m, src)
}
func (m *RegisteRequest) XXX_Size() int {
	return xxx_messageInfo_RegisteRequest.Size(m)
}
func (m *RegisteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteRequest proto.InternalMessageInfo

func (m *RegisteRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisteRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisteResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Player               *Player      `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisteResponse) Reset()         { *m = RegisteResponse{} }
func (m *RegisteResponse) String() string { return proto.CompactTextString(m) }
func (*RegisteResponse) ProtoMessage()    {}
func (*RegisteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *RegisteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteResponse.Unmarshal(m, b)
}
func (m *RegisteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteResponse.Marshal(b, m, deterministic)
}
func (m *RegisteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteResponse.Merge(m, src)
}
func (m *RegisteResponse) XXX_Size() int {
	return xxx_messageInfo_RegisteResponse.Size(m)
}
func (m *RegisteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteResponse proto.InternalMessageInfo

func (m *RegisteResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *RegisteResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *RegisteResponse) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

//大区列表
type ZoneRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneRequest) Reset()         { *m = ZoneRequest{} }
func (m *ZoneRequest) String() string { return proto.CompactTextString(m) }
func (*ZoneRequest) ProtoMessage()    {}
func (*ZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *ZoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneRequest.Unmarshal(m, b)
}
func (m *ZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneRequest.Marshal(b, m, deterministic)
}
func (m *ZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneRequest.Merge(m, src)
}
func (m *ZoneRequest) XXX_Size() int {
	return xxx_messageInfo_ZoneRequest.Size(m)
}
func (m *ZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneRequest proto.InternalMessageInfo

type ZoneResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Zones                []*Zone      `protobuf:"bytes,3,rep,name=zones,proto3" json:"zones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ZoneResponse) Reset()         { *m = ZoneResponse{} }
func (m *ZoneResponse) String() string { return proto.CompactTextString(m) }
func (*ZoneResponse) ProtoMessage()    {}
func (*ZoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{5}
}

func (m *ZoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneResponse.Unmarshal(m, b)
}
func (m *ZoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneResponse.Marshal(b, m, deterministic)
}
func (m *ZoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneResponse.Merge(m, src)
}
func (m *ZoneResponse) XXX_Size() int {
	return xxx_messageInfo_ZoneResponse.Size(m)
}
func (m *ZoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneResponse proto.InternalMessageInfo

func (m *ZoneResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *ZoneResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *ZoneResponse) GetZones() []*Zone {
	if m != nil {
		return m.Zones
	}
	return nil
}

type Player struct {
	UserId               string    `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	BaseInfo             *BaseInfo `protobuf:"bytes,3,opt,name=BaseInfo,proto3" json:"BaseInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{6}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetBaseInfo() *BaseInfo {
	if m != nil {
		return m.BaseInfo
	}
	return nil
}

type BaseInfo struct {
	Gold                 int32    `protobuf:"varint,1,opt,name=Gold,proto3" json:"Gold,omitempty"`
	Diamond              int32    `protobuf:"varint,2,opt,name=Diamond,proto3" json:"Diamond,omitempty"`
	Exp                  int32    `protobuf:"varint,3,opt,name=Exp,proto3" json:"Exp,omitempty"`
	Power                int32    `protobuf:"varint,4,opt,name=Power,proto3" json:"Power,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=Level,proto3" json:"Level,omitempty"`
	LevelUpExp           int32    `protobuf:"varint,6,opt,name=LevelUpExp,proto3" json:"LevelUpExp,omitempty"`
	MaxPower             int32    `protobuf:"varint,7,opt,name=MaxPower,proto3" json:"MaxPower,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfo) Reset()         { *m = BaseInfo{} }
func (m *BaseInfo) String() string { return proto.CompactTextString(m) }
func (*BaseInfo) ProtoMessage()    {}
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{7}
}

func (m *BaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo.Unmarshal(m, b)
}
func (m *BaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo.Marshal(b, m, deterministic)
}
func (m *BaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo.Merge(m, src)
}
func (m *BaseInfo) XXX_Size() int {
	return xxx_messageInfo_BaseInfo.Size(m)
}
func (m *BaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo proto.InternalMessageInfo

func (m *BaseInfo) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *BaseInfo) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *BaseInfo) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *BaseInfo) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *BaseInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *BaseInfo) GetLevelUpExp() int32 {
	if m != nil {
		return m.LevelUpExp
	}
	return 0
}

func (m *BaseInfo) GetMaxPower() int32 {
	if m != nil {
		return m.MaxPower
	}
	return 0
}

type Zone struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	IsNew                bool     `protobuf:"varint,3,opt,name=IsNew,proto3" json:"IsNew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{8}
}

func (m *Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zone.Unmarshal(m, b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
}
func (m *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(m, src)
}
func (m *Zone) XXX_Size() int {
	return xxx_messageInfo_Zone.Size(m)
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

func (m *Zone) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Zone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Zone) GetIsNew() bool {
	if m != nil {
		return m.IsNew
	}
	return false
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "msg.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "msg.LoginResponse")
	proto.RegisterType((*RegisteRequest)(nil), "msg.RegisteRequest")
	proto.RegisterType((*RegisteResponse)(nil), "msg.RegisteResponse")
	proto.RegisterType((*ZoneRequest)(nil), "msg.ZoneRequest")
	proto.RegisterType((*ZoneResponse)(nil), "msg.ZoneResponse")
	proto.RegisterType((*Player)(nil), "msg.Player")
	proto.RegisterType((*BaseInfo)(nil), "msg.BaseInfo")
	proto.RegisterType((*Zone)(nil), "msg.Zone")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0x15, 0xf8, 0x03, 0x18, 0x03, 0x6d, 0x57, 0xa8, 0xb2, 0x50, 0xd5, 0x22, 0x57, 0x95, 0xe8,
	0x85, 0x03, 0xfd, 0x03, 0x55, 0x0b, 0x89, 0x90, 0x08, 0x42, 0x2b, 0x71, 0xc9, 0x25, 0x72, 0xf0,
	0xc4, 0x42, 0xb2, 0xbd, 0xce, 0xae, 0x09, 0x90, 0xfc, 0xab, 0xfc, 0xc2, 0x68, 0x67, 0x6d, 0x27,
	0x97, 0x9c, 0x12, 0xe5, 0x36, 0xef, 0xbd, 0xd1, 0x9b, 0x99, 0xb7, 0x36, 0x78, 0x89, 0x88, 0x77,
	0xd9, 0x24, 0x97, 0xa2, 0x10, 0xcc, 0x4a, 0x55, 0x3c, 0xec, 0xa0, 0x94, 0x06, 0x07, 0x33, 0xe8,
	0x2e, 0xb5, 0xcc, 0xf1, 0x76, 0x8f, 0xaa, 0x60, 0x3e, 0xb4, 0xc2, 0xed, 0x56, 0xec, 0xb3, 0xc2,
	0x6f, 0x8c, 0x1a, 0xe3, 0x0e, 0xaf, 0x20, 0x1b, 0x42, 0x3b, 0x0f, 0x95, 0x3a, 0x08, 0x19, 0xf9,
	0x4d, 0x92, 0x6a, 0x1c, 0x9c, 0xa0, 0x57, 0xba, 0xa8, 0x5c, 0x64, 0x0a, 0xd9, 0x2f, 0xb0, 0xb7,
	0x22, 0x42, 0xf2, 0xe8, 0x4f, 0xbf, 0x4c, 0x52, 0x15, 0x4f, 0x2a, 0xf1, 0xbf, 0x88, 0x90, 0x93,
	0xcc, 0xbe, 0x81, 0x85, 0x52, 0x92, 0x9d, 0x37, 0x05, 0xea, 0x9a, 0x4b, 0x29, 0x24, 0xd7, 0x34,
	0xfb, 0x09, 0x6e, 0x9e, 0x84, 0x27, 0x94, 0xbe, 0x45, 0x0d, 0x1e, 0x35, 0xac, 0x89, 0xe2, 0xa5,
	0x14, 0x9c, 0x41, 0x9f, 0x63, 0xbc, 0x53, 0x05, 0xbe, 0xed, 0x84, 0x07, 0xf8, 0x54, 0xfb, 0x7c,
	0xf8, 0x11, 0x3d, 0xf0, 0x2e, 0x45, 0x56, 0x5d, 0x10, 0x14, 0xd0, 0x35, 0xf0, 0x3d, 0x17, 0xf9,
	0x01, 0xce, 0xbd, 0xc8, 0x50, 0xf9, 0xd6, 0xc8, 0x1a, 0x7b, 0xd3, 0x0e, 0xe9, 0x34, 0xc6, 0xf0,
	0xc1, 0x15, 0xb8, 0x66, 0x2d, 0xf6, 0x15, 0xdc, 0x8d, 0x42, 0xb9, 0x88, 0xca, 0x00, 0x4b, 0xc4,
	0x18, 0xd8, 0xab, 0x30, 0xc5, 0x32, 0x3b, 0xaa, 0xd9, 0x6f, 0x68, 0xff, 0x0b, 0x15, 0x2e, 0xb2,
	0x1b, 0x51, 0x5e, 0xd8, 0x23, 0xe7, 0x8a, 0xe4, 0xb5, 0x1c, 0x3c, 0x36, 0x9e, 0x7b, 0xb5, 0xd7,
	0xb9, 0x48, 0xcc, 0x04, 0x87, 0x53, 0xad, 0x5f, 0x6e, 0xb6, 0x0b, 0x53, 0x91, 0x99, 0xe7, 0x71,
	0x78, 0x05, 0xd9, 0x67, 0xb0, 0xe6, 0xc7, 0x9c, 0x06, 0x38, 0x5c, 0x97, 0x6c, 0x00, 0xce, 0x5a,
	0x1c, 0x50, 0xfa, 0x36, 0x71, 0x06, 0x68, 0x76, 0x89, 0x77, 0x98, 0xf8, 0x8e, 0x61, 0x09, 0xb0,
	0xef, 0x00, 0x54, 0x6c, 0x72, 0x6d, 0xe2, 0x92, 0xf4, 0x82, 0xd1, 0xdf, 0xc5, 0x45, 0x78, 0x34,
	0x76, 0x2d, 0x52, 0x6b, 0x1c, 0xfc, 0x05, 0x5b, 0x87, 0xc4, 0xfa, 0xd0, 0xac, 0xf3, 0x68, 0xbe,
	0x92, 0xc5, 0x00, 0x9c, 0x85, 0x5a, 0xe1, 0x81, 0xf6, 0x6c, 0x73, 0x03, 0xae, 0x5d, 0xfa, 0xd3,
	0xfe, 0x3c, 0x05, 0x00, 0x00, 0xff, 0xff, 0xff, 0x86, 0xc8, 0xd4, 0x88, 0x03, 0x00, 0x00,
}
