// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 登录
type LoginRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Player               *Player      `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *LoginResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *LoginResponse) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

// 注册
type RegisteRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisteRequest) Reset()         { *m = RegisteRequest{} }
func (m *RegisteRequest) String() string { return proto.CompactTextString(m) }
func (*RegisteRequest) ProtoMessage()    {}
func (*RegisteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *RegisteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteRequest.Unmarshal(m, b)
}
func (m *RegisteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteRequest.Marshal(b, m, deterministic)
}
func (m *RegisteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteRequest.Merge(m, src)
}
func (m *RegisteRequest) XXX_Size() int {
	return xxx_messageInfo_RegisteRequest.Size(m)
}
func (m *RegisteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteRequest proto.InternalMessageInfo

func (m *RegisteRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisteRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisteResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Player               *Player      `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisteResponse) Reset()         { *m = RegisteResponse{} }
func (m *RegisteResponse) String() string { return proto.CompactTextString(m) }
func (*RegisteResponse) ProtoMessage()    {}
func (*RegisteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *RegisteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteResponse.Unmarshal(m, b)
}
func (m *RegisteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteResponse.Marshal(b, m, deterministic)
}
func (m *RegisteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteResponse.Merge(m, src)
}
func (m *RegisteResponse) XXX_Size() int {
	return xxx_messageInfo_RegisteResponse.Size(m)
}
func (m *RegisteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteResponse proto.InternalMessageInfo

func (m *RegisteResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *RegisteResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *RegisteResponse) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type Player struct {
	UserId               string    `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	BaseInfo             *BaseInfo `protobuf:"bytes,3,opt,name=BaseInfo,proto3" json:"BaseInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetBaseInfo() *BaseInfo {
	if m != nil {
		return m.BaseInfo
	}
	return nil
}

type BaseInfo struct {
	Gold                 int32    `protobuf:"varint,1,opt,name=Gold,proto3" json:"Gold,omitempty"`
	Diamond              int32    `protobuf:"varint,2,opt,name=Diamond,proto3" json:"Diamond,omitempty"`
	Exp                  int32    `protobuf:"varint,3,opt,name=Exp,proto3" json:"Exp,omitempty"`
	Power                int32    `protobuf:"varint,4,opt,name=Power,proto3" json:"Power,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=Level,proto3" json:"Level,omitempty"`
	LevelUpExp           int32    `protobuf:"varint,6,opt,name=LevelUpExp,proto3" json:"LevelUpExp,omitempty"`
	MaxPower             int32    `protobuf:"varint,7,opt,name=MaxPower,proto3" json:"MaxPower,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfo) Reset()         { *m = BaseInfo{} }
func (m *BaseInfo) String() string { return proto.CompactTextString(m) }
func (*BaseInfo) ProtoMessage()    {}
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{5}
}

func (m *BaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo.Unmarshal(m, b)
}
func (m *BaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo.Marshal(b, m, deterministic)
}
func (m *BaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo.Merge(m, src)
}
func (m *BaseInfo) XXX_Size() int {
	return xxx_messageInfo_BaseInfo.Size(m)
}
func (m *BaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo proto.InternalMessageInfo

func (m *BaseInfo) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *BaseInfo) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *BaseInfo) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *BaseInfo) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *BaseInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *BaseInfo) GetLevelUpExp() int32 {
	if m != nil {
		return m.LevelUpExp
	}
	return 0
}

func (m *BaseInfo) GetMaxPower() int32 {
	if m != nil {
		return m.MaxPower
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "msg.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "msg.LoginResponse")
	proto.RegisterType((*RegisteRequest)(nil), "msg.RegisteRequest")
	proto.RegisterType((*RegisteResponse)(nil), "msg.RegisteResponse")
	proto.RegisterType((*Player)(nil), "msg.Player")
	proto.RegisterType((*BaseInfo)(nil), "msg.BaseInfo")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xdd, 0x4a, 0xe3, 0x40,
	0x14, 0xc7, 0xe9, 0xa6, 0x49, 0xdb, 0xd3, 0x6d, 0x77, 0x77, 0x58, 0x24, 0x14, 0x11, 0x89, 0x08,
	0x7a, 0xd3, 0x8b, 0xfa, 0x06, 0xda, 0x2a, 0x85, 0x2a, 0x65, 0xa0, 0xd7, 0x32, 0x36, 0xc7, 0x50,
	0x48, 0x72, 0xe2, 0x4c, 0x6a, 0x5b, 0x7c, 0x2b, 0x9f, 0x50, 0xe6, 0x4c, 0x12, 0xbd, 0x17, 0xbc,
	0x3b, 0xff, 0x0f, 0x7e, 0x33, 0x73, 0x12, 0xe8, 0xa7, 0x94, 0x6c, 0xf2, 0x71, 0xa1, 0xa9, 0x24,
	0xe1, 0x65, 0x26, 0x19, 0xf5, 0x50, 0x6b, 0xa7, 0xa3, 0x29, 0xfc, 0x5e, 0xd8, 0x58, 0xe2, 0xcb,
	0x16, 0x4d, 0x29, 0x42, 0xe8, 0xa8, 0xf5, 0x9a, 0xb6, 0x79, 0x19, 0xb6, 0x4e, 0x5b, 0x17, 0x3d,
	0x59, 0x4b, 0x31, 0x82, 0x6e, 0xa1, 0x8c, 0xd9, 0x91, 0x8e, 0xc3, 0x5f, 0x1c, 0x35, 0x3a, 0x3a,
	0xc0, 0xa0, 0xa2, 0x98, 0x82, 0x72, 0x83, 0xe2, 0x1c, 0xda, 0x6b, 0x8a, 0x91, 0x19, 0xc3, 0xc9,
	0xbf, 0x71, 0x66, 0x92, 0x71, 0x1d, 0xde, 0x50, 0x8c, 0x92, 0x63, 0x71, 0x0c, 0x1e, 0x6a, 0xcd,
	0xb8, 0xfe, 0x04, 0xb8, 0x35, 0xd3, 0x9a, 0xb4, 0xb4, 0xb6, 0x38, 0x83, 0xa0, 0x48, 0xd5, 0x01,
	0x75, 0xe8, 0x71, 0xa1, 0xcf, 0x85, 0x25, 0x5b, 0xb2, 0x8a, 0xa2, 0x5b, 0x18, 0x4a, 0x4c, 0x36,
	0xa6, 0xc4, 0xef, 0x3d, 0xe1, 0x0d, 0xfe, 0x34, 0x9c, 0x1f, 0x7f, 0xc4, 0x23, 0x04, 0xce, 0x11,
	0x47, 0x10, 0xac, 0x0c, 0xea, 0x79, 0x5c, 0xdd, 0xbd, 0x52, 0x42, 0x40, 0xfb, 0x41, 0x65, 0x58,
	0x5d, 0x9b, 0x67, 0x71, 0x09, 0xdd, 0x6b, 0x65, 0x70, 0x9e, 0x3f, 0x53, 0x05, 0x1f, 0x30, 0xbc,
	0x36, 0x65, 0x13, 0x47, 0xef, 0xad, 0xcf, 0xae, 0x65, 0xdd, 0x51, 0xea, 0x4e, 0xf0, 0x25, 0xcf,
	0x76, 0x69, 0xd3, 0x8d, 0xca, 0x28, 0x77, 0x9b, 0xf1, 0x65, 0x2d, 0xc5, 0x5f, 0xf0, 0x66, 0xfb,
	0x82, 0x0f, 0xf0, 0xa5, 0x1d, 0xc5, 0x7f, 0xf0, 0x97, 0xb4, 0x43, 0x1d, 0xb6, 0xd9, 0x73, 0xc2,
	0xba, 0x0b, 0x7c, 0xc5, 0x34, 0xf4, 0x9d, 0xcb, 0x42, 0x9c, 0x00, 0xf0, 0xb0, 0x2a, 0x2c, 0x24,
	0xe0, 0xe8, 0x8b, 0x63, 0x3f, 0xc9, 0xbd, 0xda, 0x3b, 0x5c, 0x87, 0xd3, 0x46, 0x3f, 0x05, 0xfc,
	0x8b, 0x5e, 0x7d, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xdb, 0x02, 0xe9, 0xc1, 0x02, 0x00, 0x00,
}
