// Code generated by protoc-gen-go. DO NOT EDIT.
// source: map.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChapterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChapterRequest) Reset()         { *m = ChapterRequest{} }
func (m *ChapterRequest) String() string { return proto.CompactTextString(m) }
func (*ChapterRequest) ProtoMessage()    {}
func (*ChapterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_670a3ee274ba020a, []int{0}
}

func (m *ChapterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterRequest.Unmarshal(m, b)
}
func (m *ChapterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterRequest.Marshal(b, m, deterministic)
}
func (m *ChapterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterRequest.Merge(m, src)
}
func (m *ChapterRequest) XXX_Size() int {
	return xxx_messageInfo_ChapterRequest.Size(m)
}
func (m *ChapterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterRequest proto.InternalMessageInfo

type ChapterResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Chapters             []*Chapter   `protobuf:"bytes,3,rep,name=chapters,proto3" json:"chapters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChapterResponse) Reset()         { *m = ChapterResponse{} }
func (m *ChapterResponse) String() string { return proto.CompactTextString(m) }
func (*ChapterResponse) ProtoMessage()    {}
func (*ChapterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_670a3ee274ba020a, []int{1}
}

func (m *ChapterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterResponse.Unmarshal(m, b)
}
func (m *ChapterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterResponse.Marshal(b, m, deterministic)
}
func (m *ChapterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterResponse.Merge(m, src)
}
func (m *ChapterResponse) XXX_Size() int {
	return xxx_messageInfo_ChapterResponse.Size(m)
}
func (m *ChapterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterResponse proto.InternalMessageInfo

func (m *ChapterResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *ChapterResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *ChapterResponse) GetChapters() []*Chapter {
	if m != nil {
		return m.Chapters
	}
	return nil
}

type Chapter struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	IsOpen               bool     `protobuf:"varint,3,opt,name=IsOpen,proto3" json:"IsOpen,omitempty"`
	Star                 int32    `protobuf:"varint,4,opt,name=Star,proto3" json:"Star,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	GuanKaNum            int32    `protobuf:"varint,6,opt,name=GuanKaNum,proto3" json:"GuanKaNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chapter) Reset()         { *m = Chapter{} }
func (m *Chapter) String() string { return proto.CompactTextString(m) }
func (*Chapter) ProtoMessage()    {}
func (*Chapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_670a3ee274ba020a, []int{2}
}

func (m *Chapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chapter.Unmarshal(m, b)
}
func (m *Chapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chapter.Marshal(b, m, deterministic)
}
func (m *Chapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chapter.Merge(m, src)
}
func (m *Chapter) XXX_Size() int {
	return xxx_messageInfo_Chapter.Size(m)
}
func (m *Chapter) XXX_DiscardUnknown() {
	xxx_messageInfo_Chapter.DiscardUnknown(m)
}

var xxx_messageInfo_Chapter proto.InternalMessageInfo

func (m *Chapter) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Chapter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chapter) GetIsOpen() bool {
	if m != nil {
		return m.IsOpen
	}
	return false
}

func (m *Chapter) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *Chapter) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Chapter) GetGuanKaNum() int32 {
	if m != nil {
		return m.GuanKaNum
	}
	return 0
}

type GuanKaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuanKaRequest) Reset()         { *m = GuanKaRequest{} }
func (m *GuanKaRequest) String() string { return proto.CompactTextString(m) }
func (*GuanKaRequest) ProtoMessage()    {}
func (*GuanKaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_670a3ee274ba020a, []int{3}
}

func (m *GuanKaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuanKaRequest.Unmarshal(m, b)
}
func (m *GuanKaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuanKaRequest.Marshal(b, m, deterministic)
}
func (m *GuanKaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuanKaRequest.Merge(m, src)
}
func (m *GuanKaRequest) XXX_Size() int {
	return xxx_messageInfo_GuanKaRequest.Size(m)
}
func (m *GuanKaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GuanKaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GuanKaRequest proto.InternalMessageInfo

type GuanKaResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	GuanKas              []*GuanKa    `protobuf:"bytes,3,rep,name=guanKas,proto3" json:"guanKas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GuanKaResponse) Reset()         { *m = GuanKaResponse{} }
func (m *GuanKaResponse) String() string { return proto.CompactTextString(m) }
func (*GuanKaResponse) ProtoMessage()    {}
func (*GuanKaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_670a3ee274ba020a, []int{4}
}

func (m *GuanKaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuanKaResponse.Unmarshal(m, b)
}
func (m *GuanKaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuanKaResponse.Marshal(b, m, deterministic)
}
func (m *GuanKaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuanKaResponse.Merge(m, src)
}
func (m *GuanKaResponse) XXX_Size() int {
	return xxx_messageInfo_GuanKaResponse.Size(m)
}
func (m *GuanKaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GuanKaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GuanKaResponse proto.InternalMessageInfo

func (m *GuanKaResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *GuanKaResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GuanKaResponse) GetGuanKas() []*GuanKa {
	if m != nil {
		return m.GuanKas
	}
	return nil
}

type GuanKa struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ChapterId            int32    `protobuf:"varint,3,opt,name=ChapterId,proto3" json:"ChapterId,omitempty"`
	Earn                 *Earn    `protobuf:"bytes,4,opt,name=Earn,proto3" json:"Earn,omitempty"`
	Expend               *Expend  `protobuf:"bytes,5,opt,name=Expend,proto3" json:"Expend,omitempty"`
	IsOpen               bool     `protobuf:"varint,6,opt,name=IsOpen,proto3" json:"IsOpen,omitempty"`
	Star                 int32    `protobuf:"varint,7,opt,name=Star,proto3" json:"Star,omitempty"`
	Status               int32    `protobuf:"varint,8,opt,name=Status,proto3" json:"Status,omitempty"`
	Times                int32    `protobuf:"varint,9,opt,name=Times,proto3" json:"Times,omitempty"`
	TotalTimes           int32    `protobuf:"varint,10,opt,name=TotalTimes,proto3" json:"TotalTimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuanKa) Reset()         { *m = GuanKa{} }
func (m *GuanKa) String() string { return proto.CompactTextString(m) }
func (*GuanKa) ProtoMessage()    {}
func (*GuanKa) Descriptor() ([]byte, []int) {
	return fileDescriptor_670a3ee274ba020a, []int{5}
}

func (m *GuanKa) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuanKa.Unmarshal(m, b)
}
func (m *GuanKa) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuanKa.Marshal(b, m, deterministic)
}
func (m *GuanKa) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuanKa.Merge(m, src)
}
func (m *GuanKa) XXX_Size() int {
	return xxx_messageInfo_GuanKa.Size(m)
}
func (m *GuanKa) XXX_DiscardUnknown() {
	xxx_messageInfo_GuanKa.DiscardUnknown(m)
}

var xxx_messageInfo_GuanKa proto.InternalMessageInfo

func (m *GuanKa) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GuanKa) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GuanKa) GetChapterId() int32 {
	if m != nil {
		return m.ChapterId
	}
	return 0
}

func (m *GuanKa) GetEarn() *Earn {
	if m != nil {
		return m.Earn
	}
	return nil
}

func (m *GuanKa) GetExpend() *Expend {
	if m != nil {
		return m.Expend
	}
	return nil
}

func (m *GuanKa) GetIsOpen() bool {
	if m != nil {
		return m.IsOpen
	}
	return false
}

func (m *GuanKa) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *GuanKa) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GuanKa) GetTimes() int32 {
	if m != nil {
		return m.Times
	}
	return 0
}

func (m *GuanKa) GetTotalTimes() int32 {
	if m != nil {
		return m.TotalTimes
	}
	return 0
}

type Earn struct {
	ItemIds              []string `protobuf:"bytes,1,rep,name=ItemIds,proto3" json:"ItemIds,omitempty"`
	HeroExp              int32    `protobuf:"varint,2,opt,name=HeroExp,proto3" json:"HeroExp,omitempty"`
	PlayerExp            int32    `protobuf:"varint,3,opt,name=PlayerExp,proto3" json:"PlayerExp,omitempty"`
	Gold                 int32    `protobuf:"varint,4,opt,name=Gold,proto3" json:"Gold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Earn) Reset()         { *m = Earn{} }
func (m *Earn) String() string { return proto.CompactTextString(m) }
func (*Earn) ProtoMessage()    {}
func (*Earn) Descriptor() ([]byte, []int) {
	return fileDescriptor_670a3ee274ba020a, []int{6}
}

func (m *Earn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Earn.Unmarshal(m, b)
}
func (m *Earn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Earn.Marshal(b, m, deterministic)
}
func (m *Earn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Earn.Merge(m, src)
}
func (m *Earn) XXX_Size() int {
	return xxx_messageInfo_Earn.Size(m)
}
func (m *Earn) XXX_DiscardUnknown() {
	xxx_messageInfo_Earn.DiscardUnknown(m)
}

var xxx_messageInfo_Earn proto.InternalMessageInfo

func (m *Earn) GetItemIds() []string {
	if m != nil {
		return m.ItemIds
	}
	return nil
}

func (m *Earn) GetHeroExp() int32 {
	if m != nil {
		return m.HeroExp
	}
	return 0
}

func (m *Earn) GetPlayerExp() int32 {
	if m != nil {
		return m.PlayerExp
	}
	return 0
}

func (m *Earn) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

type Expend struct {
	Power                int32    `protobuf:"varint,1,opt,name=Power,proto3" json:"Power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Expend) Reset()         { *m = Expend{} }
func (m *Expend) String() string { return proto.CompactTextString(m) }
func (*Expend) ProtoMessage()    {}
func (*Expend) Descriptor() ([]byte, []int) {
	return fileDescriptor_670a3ee274ba020a, []int{7}
}

func (m *Expend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expend.Unmarshal(m, b)
}
func (m *Expend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expend.Marshal(b, m, deterministic)
}
func (m *Expend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expend.Merge(m, src)
}
func (m *Expend) XXX_Size() int {
	return xxx_messageInfo_Expend.Size(m)
}
func (m *Expend) XXX_DiscardUnknown() {
	xxx_messageInfo_Expend.DiscardUnknown(m)
}

var xxx_messageInfo_Expend proto.InternalMessageInfo

func (m *Expend) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func init() {
	proto.RegisterType((*ChapterRequest)(nil), "msg.ChapterRequest")
	proto.RegisterType((*ChapterResponse)(nil), "msg.ChapterResponse")
	proto.RegisterType((*Chapter)(nil), "msg.Chapter")
	proto.RegisterType((*GuanKaRequest)(nil), "msg.GuanKaRequest")
	proto.RegisterType((*GuanKaResponse)(nil), "msg.GuanKaResponse")
	proto.RegisterType((*GuanKa)(nil), "msg.GuanKa")
	proto.RegisterType((*Earn)(nil), "msg.Earn")
	proto.RegisterType((*Expend)(nil), "msg.Expend")
}

func init() { proto.RegisterFile("map.proto", fileDescriptor_670a3ee274ba020a) }

var fileDescriptor_670a3ee274ba020a = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x6a, 0x1b, 0x31,
	0x10, 0x86, 0x59, 0xaf, 0x77, 0xed, 0x1d, 0xb7, 0x4e, 0x2b, 0x4a, 0x11, 0xc5, 0x0d, 0xcb, 0x96,
	0xc0, 0x9e, 0x7c, 0x70, 0x1f, 0x21, 0x98, 0x74, 0x29, 0xa4, 0x41, 0xc9, 0x0b, 0xa8, 0xd1, 0xe0,
	0x16, 0xbc, 0xab, 0xad, 0x24, 0xd3, 0x14, 0x7a, 0xe8, 0xb1, 0xb7, 0xbe, 0x72, 0xd1, 0x48, 0x72,
	0x52, 0xc8, 0xa1, 0x87, 0xdc, 0xe6, 0xff, 0xff, 0xb1, 0x66, 0xf8, 0xc6, 0x0b, 0x55, 0x2f, 0xc7,
	0xf5, 0x68, 0xb4, 0xd3, 0x2c, 0xef, 0xed, 0xee, 0x4d, 0x85, 0xc6, 0x04, 0xdd, 0xbc, 0x80, 0xe5,
	0xf9, 0x17, 0x39, 0x3a, 0x34, 0x02, 0xbf, 0x1d, 0xd0, 0xba, 0xe6, 0x57, 0x06, 0x27, 0x47, 0xcb,
	0x8e, 0x7a, 0xb0, 0xc8, 0xce, 0x60, 0x7a, 0xab, 0x15, 0xf2, 0xac, 0xce, 0xda, 0xe5, 0xe6, 0xe5,
	0xba, 0xb7, 0xbb, 0x75, 0x0a, 0xcf, 0xb5, 0x42, 0x41, 0x31, 0x5b, 0x41, 0x8e, 0xc6, 0xf0, 0x49,
	0x9d, 0xb5, 0x8b, 0x0d, 0x50, 0xd7, 0xd6, 0x18, 0x6d, 0x84, 0xb7, 0x59, 0x0b, 0xf3, 0xdb, 0xf0,
	0xae, 0xe5, 0x79, 0x9d, 0xb7, 0x8b, 0xcd, 0x33, 0x6a, 0x49, 0xc3, 0x8e, 0x69, 0xf3, 0x27, 0x83,
	0x59, 0x74, 0xd9, 0x12, 0x26, 0x9d, 0xa2, 0xc1, 0x85, 0x98, 0x74, 0x8a, 0x31, 0x98, 0x5e, 0xca,
	0x1e, 0x69, 0x48, 0x25, 0xa8, 0x66, 0xaf, 0xa1, 0xec, 0xec, 0xa7, 0x11, 0x07, 0x9e, 0xd7, 0x59,
	0x3b, 0x17, 0x51, 0xf9, 0xde, 0x6b, 0x27, 0x0d, 0x9f, 0xd2, 0xaf, 0xa9, 0xf6, 0xbd, 0xd7, 0x4e,
	0xba, 0x83, 0xe5, 0x05, 0xb9, 0x51, 0xb1, 0x15, 0x54, 0x17, 0x07, 0x39, 0x7c, 0x94, 0x97, 0x87,
	0x9e, 0x97, 0x14, 0xdd, 0x1b, 0xcd, 0x09, 0x3c, 0x0f, 0x22, 0x51, 0xfa, 0x09, 0xcb, 0x64, 0x3c,
	0x25, 0xa3, 0x33, 0x98, 0xed, 0xe8, 0xd9, 0x84, 0x68, 0x41, 0x1d, 0x71, 0x54, 0xca, 0x9a, 0xdf,
	0x13, 0x28, 0x83, 0xf7, 0x5f, 0x7c, 0x56, 0x50, 0x45, 0x9c, 0x9d, 0x22, 0x44, 0x85, 0xb8, 0x37,
	0xd8, 0x5b, 0x98, 0x6e, 0xa5, 0x19, 0x88, 0xd2, 0x62, 0x53, 0x85, 0x95, 0xa4, 0x19, 0x04, 0xd9,
	0xec, 0x1d, 0x94, 0xdb, 0xbb, 0x11, 0x07, 0x45, 0xc0, 0xd2, 0x46, 0xc1, 0x12, 0x31, 0x7a, 0x70,
	0x81, 0xf2, 0xd1, 0x0b, 0xcc, 0x1e, 0xbd, 0xc0, 0xfc, 0x9f, 0x0b, 0xbc, 0x82, 0xe2, 0xe6, 0x6b,
	0x8f, 0x96, 0x57, 0x64, 0x07, 0xc1, 0x4e, 0x01, 0x6e, 0xb4, 0x93, 0xfb, 0x10, 0x01, 0x45, 0x0f,
	0x9c, 0x66, 0x1f, 0xb6, 0x67, 0x1c, 0x66, 0x9d, 0xc3, 0xbe, 0x53, 0x96, 0x67, 0x75, 0xde, 0x56,
	0x22, 0x49, 0x9f, 0x7c, 0x40, 0xa3, 0xb7, 0x77, 0x23, 0x41, 0x29, 0x44, 0x92, 0x9e, 0xcb, 0xd5,
	0x5e, 0xfe, 0x40, 0xe3, 0xb3, 0xc8, 0xe5, 0x68, 0xf8, 0xdd, 0x2f, 0xf4, 0x5e, 0xa5, 0x7f, 0x8f,
	0xaf, 0x9b, 0xd3, 0x04, 0xc3, 0x6f, 0x7b, 0xa5, 0xbf, 0xa3, 0x89, 0xe8, 0x83, 0xf8, 0x5c, 0xd2,
	0x57, 0xf5, 0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x23, 0xe7, 0xe9, 0xa4, 0x72, 0x03, 0x00,
	0x00,
}
