package msg

import (
	"github.com/name5566/leaf/network/protobuf"
)

// Processor .
var Processor = protobuf.NewProcessor()

func init() {
	Processor.SetByteOrder(true)
	Processor.Register(100, &LoginRequest{})
	Processor.Register(101, &LoginResponse{})
	Processor.Register(102, &RegisteRequest{})
	Processor.Register(103, &RegisteResponse{})
	Processor.Register(104, &HeroRequest{})
	Processor.Register(105, &HeroResponse{})
	Processor.Register(106, &HeroRandomRequest{})
	Processor.Register(107, &HeroRandomResponse{})
	Processor.Register(108, &HeroOwnRequest{})
	Processor.Register(109, &HeroOwnResponse{})
	Processor.Register(110, &SkillRequest{})
	Processor.Register(111, &SkillResponse{})
	Processor.Register(112, &EquipRequest{})
	Processor.Register(113, &EquipResponse{})
	Processor.Register(114, &ChapterRequest{})
	Processor.Register(115, &ChapterResponse{})
	Processor.Register(116, &GuanKaRequest{})
	Processor.Register(117, &GuanKaResponse{})
	Processor.Register(118, &BattleGuanKaRequest{})
	Processor.Register(119, &BattleGuanKaResponse{})
	Processor.Register(120, &HeroSelectRequest{})
	Processor.Register(121, &HeroSelectResponse{})
	Processor.Register(122, &HeroUnSelectRequest{})
	Processor.Register(123, &HeroUnSelectResponse{})
	Processor.Register(124, &HeroSkillsRequest{})
	Processor.Register(125, &HeroSkillsResponse{})
	Processor.Register(126, &HeroEquipsRequest{})
	Processor.Register(127, &HeroEquipsResponse{})
	Processor.Register(128, &SkillUpgradeRequest{})
	Processor.Register(129, &SkillUpgradeResponse{})
	Processor.Register(130, &ZoneRequest{})
	Processor.Register(131, &ZoneResponse{})
	Processor.Register(132, &BattleStartRequest{})
	Processor.Register(133, &BattleStartResponse{})
	Processor.Register(134, &BattleResultRequest{})
	Processor.Register(135, &BattleResultResponse{})
	Processor.Register(136, &GroupOwnRequest{})
	Processor.Register(137, &GroupOwnResponse{})
	Processor.Register(138, &GroupListRequest{})
	Processor.Register(139, &GroupListResponse{})
	Processor.Register(140, &GroupCreateRequest{})
	Processor.Register(141, &GroupCreateResponse{})
	Processor.Register(142, &GroupMembersRequest{})
	Processor.Register(143, &GroupMembersResponse{})
	Processor.Register(144, &BattleCreateRequest{})
	Processor.Register(145, &BattleCreateResponse{})
	Processor.Register(146, &HeroLotteryRequest{})
	Processor.Register(147, &HeroLotteryResponse{})
	Processor.Register(148, &ItemRequest{})
	Processor.Register(149, &ItemResponse{})
	Processor.Register(150, &GroupApplyRequest{})
	Processor.Register(151, &GroupApplyResponse{})
	Processor.Register(152, &GroupApplyMembersRequest{})
	Processor.Register(153, &GroupApplyMembersResponse{})
	Processor.Register(154, &GroupOperRequest{})
	Processor.Register(155, &GroupOperResponse{})
	Processor.Register(156, &GroupContriRequest{})
	Processor.Register(157, &GroupContriResponse{})

	Processor.Register(1000, &ChapterUpdateNotify{})
	Processor.Register(1001, &GuanKaUpdateNotify{})
	Processor.Register(1002, &PlayerInfoNotify{})
}
