// Code generated by protoc-gen-go. DO NOT EDIT.
// source: skill.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SkillRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillRequest) Reset()         { *m = SkillRequest{} }
func (m *SkillRequest) String() string { return proto.CompactTextString(m) }
func (*SkillRequest) ProtoMessage()    {}
func (*SkillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd709e691a520876, []int{0}
}

func (m *SkillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillRequest.Unmarshal(m, b)
}
func (m *SkillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillRequest.Marshal(b, m, deterministic)
}
func (m *SkillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillRequest.Merge(m, src)
}
func (m *SkillRequest) XXX_Size() int {
	return xxx_messageInfo_SkillRequest.Size(m)
}
func (m *SkillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SkillRequest proto.InternalMessageInfo

type SkillResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=msg.ResponseCode" json:"code,omitempty"`
	Err                  *Error       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Skills               []*Skill     `protobuf:"bytes,3,rep,name=skills,proto3" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SkillResponse) Reset()         { *m = SkillResponse{} }
func (m *SkillResponse) String() string { return proto.CompactTextString(m) }
func (*SkillResponse) ProtoMessage()    {}
func (*SkillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd709e691a520876, []int{1}
}

func (m *SkillResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillResponse.Unmarshal(m, b)
}
func (m *SkillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillResponse.Marshal(b, m, deterministic)
}
func (m *SkillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillResponse.Merge(m, src)
}
func (m *SkillResponse) XXX_Size() int {
	return xxx_messageInfo_SkillResponse.Size(m)
}
func (m *SkillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SkillResponse proto.InternalMessageInfo

func (m *SkillResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_FAIL
}

func (m *SkillResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *SkillResponse) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

type Skill struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Desc                 string   `protobuf:"bytes,5,opt,name=Desc,proto3" json:"Desc,omitempty"`
	IsOpen               bool     `protobuf:"varint,6,opt,name=IsOpen,proto3" json:"IsOpen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd709e691a520876, []int{2}
}

func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Skill) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Skill) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Skill) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Skill) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Skill) GetIsOpen() bool {
	if m != nil {
		return m.IsOpen
	}
	return false
}

func init() {
	proto.RegisterType((*SkillRequest)(nil), "msg.SkillRequest")
	proto.RegisterType((*SkillResponse)(nil), "msg.SkillResponse")
	proto.RegisterType((*Skill)(nil), "msg.Skill")
}

func init() { proto.RegisterFile("skill.proto", fileDescriptor_dd709e691a520876) }

var fileDescriptor_dd709e691a520876 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x49, 0xd3, 0x16, 0x77, 0x56, 0x0b, 0x0e, 0x22, 0x41, 0x3c, 0x94, 0x82, 0xd0, 0x53,
	0x0f, 0xeb, 0x23, 0xa8, 0x87, 0x82, 0x28, 0x44, 0x5f, 0x40, 0xb7, 0xc3, 0x22, 0xb6, 0x9b, 0x3a,
	0x53, 0x45, 0x8f, 0xbe, 0xb9, 0x64, 0x5a, 0xf7, 0xf6, 0xfd, 0xf9, 0x25, 0x5f, 0x08, 0xac, 0xe5,
	0xfd, 0xad, 0xef, 0x9b, 0x91, 0xc3, 0x14, 0xd0, 0x0e, 0xb2, 0xbb, 0x58, 0x11, 0xf3, 0xec, 0xab,
	0x02, 0x8e, 0x9f, 0x62, 0xed, 0xe9, 0xe3, 0x93, 0x64, 0xaa, 0xbe, 0xe1, 0x64, 0xf1, 0x32, 0x86,
	0xbd, 0x10, 0x5e, 0x41, 0xba, 0x0d, 0x1d, 0x39, 0x53, 0x9a, 0xba, 0xd8, 0x9c, 0x36, 0x83, 0xec,
	0x9a, 0xff, 0xf2, 0x26, 0x74, 0xe4, 0xb5, 0xc6, 0x4b, 0xb0, 0xc4, 0xec, 0x92, 0xd2, 0xd4, 0xeb,
	0x0d, 0x28, 0x75, 0xc7, 0x1c, 0xd8, 0xc7, 0x18, 0x2b, 0xc8, 0xf5, 0x11, 0xe2, 0x6c, 0x69, 0x0f,
	0xc0, 0x3c, 0xb4, 0x34, 0xd5, 0xaf, 0x81, 0x4c, 0x13, 0x2c, 0x20, 0x69, 0x3b, 0x1d, 0xcc, 0x7c,
	0xd2, 0x76, 0x88, 0x90, 0x3e, 0xbc, 0x0c, 0xa4, 0x97, 0xaf, 0xbc, 0x6a, 0x3c, 0x83, 0xec, 0x9e,
	0xbe, 0xa8, 0x77, 0x56, 0xb1, 0xd9, 0x44, 0xf2, 0xf9, 0x67, 0x24, 0x97, 0x6a, 0xa8, 0x3a, 0x66,
	0xb7, 0x24, 0x5b, 0x97, 0xcd, 0xa7, 0xa3, 0xc6, 0x73, 0xc8, 0x5b, 0x79, 0x1c, 0x69, 0xef, 0xf2,
	0xd2, 0xd4, 0x47, 0x7e, 0x71, 0xaf, 0xb9, 0x7e, 0xca, 0xf5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xf3, 0x19, 0x7a, 0xef, 0x33, 0x01, 0x00, 0x00,
}
